// Generated by scripts/generate-crate-descriptor.tsx
// Source: rustdoc JSON format version 57

import type { SymbolDescriptor } from "../../create-crate.js";

export const mod_alloc = {
  alloc: {
    kind: "function",
    metadata: {
      since: "1.28.0",
    },
  },
  alloc_zeroed: {
    kind: "function",
    metadata: {
      since: "1.28.0",
    },
  },
  dealloc: {
    kind: "function",
    metadata: {
      since: "1.28.0",
    },
  },
  Global: {
    kind: "struct",
    metadata: {
      since: "unstable",
    },
  },
  handle_alloc_error: {
    kind: "function",
    metadata: {
      since: "1.28.0",
    },
  },
  realloc: {
    kind: "function",
    metadata: {
      since: "1.28.0",
    },
  },
} as const satisfies Record<string, SymbolDescriptor>;
