import { describe, expect, it } from "vitest";
import {
  List,
  namekey,
  Output,
  OutputDirectory,
  OutputFile,
  render,
} from "@alloy-js/core";
import * as rust from "@alloy-js/rust";
import { AssignmentStatement, BinaryExpression } from "@alloy-js/rust";

function findFile(
  res: OutputDirectory,
  path: string,
): OutputFile & { contents: string } {
  for (const item of res.contents) {
    if (item.kind === "file" && (item.path === path || item.path.endsWith("/" + path))) {
      return item as OutputFile & { contents: string };
    }
    if (item.kind === "directory") {
      const found = findFile(item, path);
      if (found) return found;
    }
  }
  return undefined!;
}

// Refkeys matching those in src/index.tsx
const personRef = namekey("Person");
const borrowedRef = namekey("Borrowed");
const containerRef = namekey("Container");
const statusRef = namekey("Status");
const greetableRef = namekey("Greetable");
const asyncFetchableRef = namekey("AsyncFetchable");
const nameFieldRef = namekey("name");
const ageFieldRef = namekey("age");
const maxRetriesRef = namekey("MAX_RETRIES");
const defaultNameRef = namekey("DEFAULT_NAME");
const appResultRef = namekey("AppResult");

function renderExample() {
  return render(
    <Output>
      <rust.CrateDirectory name="alloy-demo" edition="2024">
        <rust.CargoToml
          version="0.1.0"
          authors={["Alloy Codegen <alloy@example.com>"]}
          description="A demo crate generated by alloy-js"
          license="MIT"
          dependencies={{
            tokio: { version: "1", features: ["rt", "macros"], optional: true },
          }}
          features={{
            "async-runtime": ["dep:tokio"],
            default: [],
          }}
        />

        <rust.SourceDirectory path="src">
          <rust.SourceFile
            path="lib.rs"
            header={<rust.InnerAttribute>allow(dead_code)</rust.InnerAttribute>}
            doc="Alloy-generated demo crate showcasing all features of @alloy-js/rust."
          >
            <rust.ModDeclaration name="models" visibility="pub" />
            <rust.ModDeclaration name="traits" visibility="pub" />
            <rust.ModDeclaration name="impls" visibility="pub" />
            <rust.ModDeclaration name="client" visibility="pub" />
            <rust.ModDeclaration name="utils" visibility="pub" />
            <>
              <rust.Cfg test />
              <rust.ModDeclaration name="tests" />
            </>

            <rust.PubUse path="crate::models" items={["Person", "Status", "Borrowed", "Container"]} />
            <rust.PubUse path="crate::traits" items={["Greetable", "AsyncFetchable"]} />
            <rust.PubUse path="crate::utils" items={["AppResult"]} />
          </rust.SourceFile>

          <rust.SourceFile path="models.rs" doc="Data models: structs with lifetimes, where clauses, enums.">
            <>
              <rust.Derive traits={["Debug", "Clone"]} />
              <rust.StructDeclaration name={personRef} visibility="pub">
                <List>
                  <rust.StructField name={nameFieldRef} type="String" visibility="pub" />
                  <rust.StructField name={ageFieldRef} type="u8" visibility="pub" />
                </List>
              </rust.StructDeclaration>
            </>

            <>
              <rust.Derive traits={["Debug"]} />
              <rust.StructDeclaration name={borrowedRef} visibility="pub" lifetimes={["a"]}>
                <List>
                  <rust.StructField
                    name={namekey("data")}
                    type={<rust.Ref lifetime="a">str</rust.Ref>}
                    visibility="pub"
                  />
                  <rust.StructField
                    name={namekey("label")}
                    type={<rust.Ref lifetime="a">str</rust.Ref>}
                    visibility="pub"
                  />
                </List>
              </rust.StructDeclaration>
            </>

            <>
              <rust.Derive traits={["Debug", "Clone"]} />
              <rust.StructDeclaration
                name={containerRef}
                visibility="pub"
              >
                <List>
                  <rust.StructField name={namekey("value")} type="String" visibility="pub" />
                  <rust.StructField
                    name={namekey("metadata")}
                    type="String"
                    visibility="pub(crate)"
                  />
                </List>
              </rust.StructDeclaration>
            </>

            <>
              <rust.Derive traits={["Debug"]} />
              <rust.EnumDeclaration name={statusRef} visibility="pub">
                <List>
                  <rust.EnumVariant name={namekey("Active")} />
                  <rust.TupleVariant name={namekey("Inactive")} types={["String"]} />
                  <rust.StructVariant name={namekey("OnLeave")}>
                    <List>
                      <rust.StructField name={namekey("reason")} type="String" />
                      <rust.StructField name={namekey("days")} type="u32" />
                    </List>
                  </rust.StructVariant>
                </List>
              </rust.EnumDeclaration>
            </>
          </rust.SourceFile>

          <rust.SourceFile path="traits.rs" doc="Trait definitions: regular, async, and conditional.">
            <rust.TraitDeclaration
              name={greetableRef}
              visibility="pub"
              doc="A trait for types that can produce a greeting."
            >
              <rust.TraitMethod name="greet" selfParam="&self" returns="String" />
              <rust.TraitMethod name="greet_with_prefix" selfParam="&self" parameters="prefix: &str" returns="String">
                <rust.MacroCall name="format">{'"{}: {}", prefix, self.greet()'}</rust.MacroCall>
              </rust.TraitMethod>
            </rust.TraitDeclaration>

            <rust.TraitDeclaration
              name={asyncFetchableRef}
              visibility="pub"
              asyncTrait
              doc="An async trait for fetching data."
            >
              <rust.TraitMethod name="fetch" selfParam="&self" returns={<rust.Result ok="String" err="String" />} async />
            </rust.TraitDeclaration>

            <>
              <rust.Cfg feature="async-runtime" />
              <rust.TraitDeclaration name={namekey("RuntimeAware")} visibility="pub">
                <rust.TraitMethod name="runtime_name" selfParam="&self" returns={<rust.Ref>str</rust.Ref>} />
              </rust.TraitDeclaration>
            </>
          </rust.SourceFile>

          <rust.SourceFile path="impls.rs" doc="Implementation blocks with match, if/else, member access, and turbofish.">
            <rust.ImplBlock type={personRef}>
              <rust.FunctionDeclaration
                name={namekey("new")}
                visibility="pub"
                parameters={[
                  { name: nameFieldRef, type: "String" },
                  { name: ageFieldRef, type: "u8" },
                ]}
                returns={personRef}
              >
                <rust.StructExpression type={personRef}>
                  <List>
                    <rust.StructFieldExpression name={nameFieldRef} />
                    <rust.StructFieldExpression name={ageFieldRef} />
                  </List>
                </rust.StructExpression>
              </rust.FunctionDeclaration>

              <rust.FunctionDeclaration
                name={namekey("describe_age")}
                visibility="pub"
                selfParam="&self"
                returns={<rust.Ref>str</rust.Ref>}
              >
                <rust.MatchExpression expr={<>self.{ageFieldRef}</>}>
                  <rust.MatchArm pattern="0..=12">"child"</rust.MatchArm>
                  <rust.MatchArm pattern="13..=19">"teenager"</rust.MatchArm>
                  <rust.MatchArm pattern="20..=64">"adult"</rust.MatchArm>
                  <rust.MatchArm pattern="_">"senior"</rust.MatchArm>
                </rust.MatchExpression>
              </rust.FunctionDeclaration>

              <rust.FunctionDeclaration
                name={namekey("is_adult")}
                visibility="pub"
                selfParam="&self"
                returns="bool"
              >
                <rust.IfExpression condition={<>self.{ageFieldRef} &gt;= 18</>} else="false">
                  true
                </rust.IfExpression>
              </rust.FunctionDeclaration>

              <rust.FunctionDeclaration
                name={namekey("name_chars")}
                visibility="pub"
                selfParam="&self"
                returns={<rust.Vec>char</rust.Vec>}
              >
                <rust.MemberExpression>
                  <rust.MemberExpression.Property id="self" />
                  <rust.MemberExpression.Property id={nameFieldRef} />
                  <rust.MemberExpression.Method id="chars" args />
                  <rust.MemberExpression.Method id="collect" args />
                </rust.MemberExpression>
              </rust.FunctionDeclaration>
            </rust.ImplBlock>

            <rust.ImplBlock type={personRef} trait={greetableRef}>
              <rust.FunctionDeclaration
                name={namekey("greet")}
                selfParam="&self"
                returns="String"
              >
                <rust.MacroCall name="format">{"\"Hello, my name is {} and I am {} years old.\", self."}{nameFieldRef}{", self."}{ageFieldRef}</rust.MacroCall>
              </rust.FunctionDeclaration>
            </rust.ImplBlock>

            <rust.FunctionDeclaration
              name={namekey("create_empty_vec")}
              visibility="pub"
              returns={<rust.Vec>String</rust.Vec>}
            >
              {"Vec::<String>::new()"}
            </rust.FunctionDeclaration>
          </rust.SourceFile>

          <rust.SourceFile path="client.rs" doc="Client functions: error handling, closures, loops, macro invocations.">
            <rust.FunctionDeclaration
              name={namekey("parse_count")}
              visibility="pub"
              parameters={[{ name: namekey("input"), type: "&str" }]}
              returns={<rust.Result ok="usize" err="std::num::ParseIntError" />}
            >
              <rust.LetDeclaration name={namekey("trimmed")}>
                <rust.MemberExpression>
                  <rust.MemberExpression.Property id="input" />
                  <rust.MemberExpression.Method id="trim" args />
                </rust.MemberExpression>
              </rust.LetDeclaration>

              <rust.LetDeclaration name={namekey("count")}>
                <rust.TryExpression>
                  <rust.MemberExpression>
                    <rust.MemberExpression.Property id="trimmed" />
                    <rust.MemberExpression.Method id="parse" args turbofish="usize" />
                  </rust.MemberExpression>
                </rust.TryExpression>
              </rust.LetDeclaration>

              Ok(count)
            </rust.FunctionDeclaration>

            <rust.FunctionDeclaration
              name={namekey("extract_names")}
              visibility="pub"
              parameters={[{ name: namekey("people"), type: "&[String]" }]}
              returns={<rust.Vec>String</rust.Vec>}
            >
              <rust.MemberExpression>
                <rust.MemberExpression.Property id="people" />
                <rust.MemberExpression.Method id="iter" args />
                <rust.MemberExpression.Method id="map" args={[
                  <rust.ClosureExpression params={[{ name: "s" }]}>
                    <rust.FunctionCall name="to_uppercase" receiver="s" args={[]} />
                  </rust.ClosureExpression>
                ]} />
                <rust.MemberExpression.Method id="collect" args />
              </rust.MemberExpression>
            </rust.FunctionDeclaration>

            <rust.FunctionDeclaration
              name={namekey("format_all")}
              visibility="pub"
              parameters={[{ name: namekey("items"), type: "&[String]" }]}
              returns={<rust.Vec>String</rust.Vec>}
            >
              <rust.MemberExpression>
                <rust.MemberExpression.Property id="items" />
                <rust.MemberExpression.Method id="iter" args />
                <rust.MemberExpression.Method id="map" args={[
                  <rust.ClosureExpression params={[{ name: "item" }]}>
                    <rust.MacroCall name="format">{"\"item: {}\", item"}</rust.MacroCall>
                  </rust.ClosureExpression>
                ]} />
                <rust.MemberExpression.Method id="collect" args />
              </rust.MemberExpression>
            </rust.FunctionDeclaration>

            <rust.FunctionDeclaration
              name={namekey("pop_all")}
              visibility="pub"
              parameters={[{ name: namekey("data"), type: "&mut Vec<i32>" }]}
              returns={<rust.Vec>i32</rust.Vec>}
            >
              <rust.LetDeclaration name={namekey("result")} mutable>
                {"Vec::new()"}
              </rust.LetDeclaration>

              <rust.WhileLetLoop pattern="Some(val)" expr="data.pop()">
                {"result.push(val);"}
              </rust.WhileLetLoop>

              result
            </rust.FunctionDeclaration>

            <rust.FunctionDeclaration
              name={namekey("retry_until_success")}
              visibility="pub"
              returns="u32"
            >
              <rust.LetDeclaration name={namekey("attempts")} mutable>0u32</rust.LetDeclaration>

              <rust.Loop label="retry">
                <AssignmentStatement target="attempts" op="+=">1</AssignmentStatement>
  
                <rust.IfExpression condition={<BinaryExpression left="attempts" op=">=" right="3" />}>
                  {"break 'retry attempts;"}
                </rust.IfExpression>
              </rust.Loop>
            </rust.FunctionDeclaration>

            <rust.FunctionDeclaration
              name={namekey("maybe_greet")}
              visibility="pub"
              parameters={[{ name: namekey("name_opt"), type: "Option<&str>" }]}
            >
              <rust.IfLetExpression pattern={<>Some(name)</>} expr="name_opt" else={<rust.MacroCall name="println">"no name provided"</rust.MacroCall>}>
                <rust.MacroCall name="println">{"\"hello, {}\", name"}</rust.MacroCall>
              </rust.IfLetExpression>
            </rust.FunctionDeclaration>

            <rust.FunctionDeclaration
              name={namekey("demo_macros")}
              visibility="pub"
              returns="String"
            >
              <rust.LetDeclaration name={namekey("numbers")}><rust.MacroCall name="vec" delimiter={"["}>1, 2, 3</rust.MacroCall></rust.LetDeclaration>

              <rust.MacroCall name="format">{"\"count: {}\", numbers.len()"}</rust.MacroCall>
            </rust.FunctionDeclaration>
          </rust.SourceFile>

          <rust.SourceFile path="utils.rs" doc="Utilities: lifetime elision, patterns, macros, constants, type aliases.">
            <rust.FunctionDeclaration
              name={namekey("first_word")}
              visibility="pub"
              parameters={[{ name: namekey("s"), type: "&str" }]}
              returns="&str"
            >
              <rust.MemberExpression>
                <rust.MemberExpression.Property id="s" />
                <rust.MemberExpression.Method id="split_whitespace" args />
                <rust.MemberExpression.Method id="next" args />
                <rust.MemberExpression.Method id="unwrap_or" args={[<>""</>]} />
              </rust.MemberExpression>
            </rust.FunctionDeclaration>

            <rust.FunctionDeclaration
              name={namekey("longest")}
              visibility="pub"
              lifetimes={["a"]}
              elideLifetimes={false}
              parameters={[
                { name: namekey("x"), type: "&'a str" },
                { name: namekey("y"), type: "&'a str" },
              ]}
              returns="&'a str"
            >
              <rust.IfExpression condition="x.len() >= y.len()" else="y">
                x
              </rust.IfExpression>
            </rust.FunctionDeclaration>

            <rust.FunctionDeclaration
              name={namekey("swap_pair")}
              visibility="pub"
              parameters={[{ name: namekey("pair"), type: "(i32, i32)" }]}
              returns="(i32, i32)"
            >
              <rust.LetDeclaration pattern={<rust.TuplePattern>{["x", "y"]}</rust.TuplePattern>}>
                pair
              </rust.LetDeclaration>

              (y, x)
            </rust.FunctionDeclaration>

            <rust.FunctionDeclaration
              name={namekey("describe_person")}
              visibility="pub"
              parameters={[{ name: namekey("person"), type: "&crate::models::Person" }]}
              returns="String"
            >
              <rust.LetDeclaration pattern={<rust.StructPattern type="crate::models::Person" fields={[{ name: "name" }, { name: "age" }]} />}>
                <rust.FunctionCall name="clone" receiver="person" args={[]} />
              </rust.LetDeclaration>

              <rust.MacroCall name="format">{'"{} is {} years old", name, age'}</rust.MacroCall>
            </rust.FunctionDeclaration>

            <rust.MacroRules name="make_greeting" visibility="pub">
              {"($name:expr) => {\n    format!(\"Welcome, {}!\", $name)\n};"}
            </rust.MacroRules>

            <rust.ConstDeclaration name={maxRetriesRef} type="u32" visibility="pub">
              5
            </rust.ConstDeclaration>

            <rust.StaticDeclaration name={defaultNameRef} type="&str" visibility="pub">
              "Unknown"
            </rust.StaticDeclaration>

            <>
              <rust.Derive traits={["Debug"]} />
              <rust.EnumDeclaration name={namekey("AppError")} visibility="pub">
                <List>
                  <rust.TupleVariant name={namekey("Parse")} types={["String"]} />
                  <rust.TupleVariant name={namekey("NotFound")} types={["String"]} />
                  <rust.TupleVariant name={namekey("Unknown")} types={["String"]} />
                </List>
              </rust.EnumDeclaration>
            </>

            <rust.ImplBlock type="AppError" trait={rust.std.fmt.Display}>
              <rust.FunctionDeclaration
                name={namekey("fmt")}
                selfParam="&self"
                parameters={[{ name: namekey("f"), type: <>{rust.std.fmt.Formatter}{"<'_>"}</>, borrow: true, mut: true }]}
                returns={rust.std.fmt.Result}
              >
                <rust.MatchExpression expr="self">
                  <rust.MatchArm pattern="AppError::Parse(msg)">
                    <rust.MacroCall name="write">{"f, \"parse error: {}\", msg"}</rust.MacroCall>
                  </rust.MatchArm>
                  <rust.MatchArm pattern="AppError::NotFound(msg)">
                    <rust.MacroCall name="write">{"f, \"not found: {}\", msg"}</rust.MacroCall>
                  </rust.MatchArm>
                  <rust.MatchArm pattern="AppError::Unknown(msg)">
                    <rust.MacroCall name="write">{"f, \"unknown error: {}\", msg"}</rust.MacroCall>
                  </rust.MatchArm>
                </rust.MatchExpression>
              </rust.FunctionDeclaration>
            </rust.ImplBlock>

            <rust.ImplBlock type="AppError" trait={rust.std.error.Error} />

            <rust.TypeAlias name={appResultRef} visibility="pub">
              {"Result<String, AppError>"}
            </rust.TypeAlias>
          </rust.SourceFile>

          <rust.SourceFile path="tests.rs">
            <List doubleHardline>
              <rust.FunctionDeclaration attributes="test" name={namekey("test_person_new")}>
                <rust.LetDeclaration name={namekey("p")}>
                  {"crate::models::Person::new(\"Alice\".to_string(), 30)"}
                </rust.LetDeclaration>
  
                <rust.MacroCall name="assert_eq">{"p.name, \"Alice\""}</rust.MacroCall>;
  
                <rust.MacroCall name="assert_eq">{"p.age, 30"}</rust.MacroCall>;
              </rust.FunctionDeclaration>

              <rust.FunctionDeclaration attributes="test" name={namekey("test_describe_age")}>
                <rust.MacroCall name="assert_eq">{"crate::models::Person::new(\"A\".to_string(), 10).describe_age(), \"child\""}</rust.MacroCall>;
  
                <rust.MacroCall name="assert_eq">{"crate::models::Person::new(\"A\".to_string(), 15).describe_age(), \"teenager\""}</rust.MacroCall>;
  
                <rust.MacroCall name="assert_eq">{"crate::models::Person::new(\"A\".to_string(), 30).describe_age(), \"adult\""}</rust.MacroCall>;
  
                <rust.MacroCall name="assert_eq">{"crate::models::Person::new(\"A\".to_string(), 70).describe_age(), \"senior\""}</rust.MacroCall>;
              </rust.FunctionDeclaration>

              <rust.FunctionDeclaration attributes="test" name={namekey("test_is_adult")}>
                <rust.MacroCall name="assert">{"!crate::models::Person::new(\"A\".to_string(), 17).is_adult()"}</rust.MacroCall>;
  
                <rust.MacroCall name="assert">{"crate::models::Person::new(\"A\".to_string(), 18).is_adult()"}</rust.MacroCall>;
              </rust.FunctionDeclaration>

              <rust.FunctionDeclaration attributes="test" name={namekey("test_swap_pair")}>
                <rust.MacroCall name="assert_eq">{"crate::utils::swap_pair((1, 2)), (2, 1)"}</rust.MacroCall>;
              </rust.FunctionDeclaration>

              <rust.FunctionDeclaration attributes="test" name={namekey("test_first_word")}>
                <rust.MacroCall name="assert_eq">{"crate::utils::first_word(\"hello world\"), \"hello\""}</rust.MacroCall>;
  
                <rust.MacroCall name="assert_eq">{"crate::utils::first_word(\"\"), \"\""}</rust.MacroCall>;
              </rust.FunctionDeclaration>

              <rust.FunctionDeclaration attributes="test" name={namekey("test_parse_count")}>
                <rust.MacroCall name="assert_eq">{"crate::client::parse_count(\"  42  \").unwrap(), 42"}</rust.MacroCall>;
  
                <rust.MacroCall name="assert">{"crate::client::parse_count(\"abc\").is_err()"}</rust.MacroCall>;
              </rust.FunctionDeclaration>

              <rust.FunctionDeclaration attributes="test" name={namekey("test_format_all")}>
                <rust.LetDeclaration name={namekey("input")}>
                  {"vec![\"a\".to_string(), \"b\".to_string()]"}
                </rust.LetDeclaration>
  
                <rust.MacroCall name="assert_eq">{"crate::client::format_all(&input), vec![\"item: a\", \"item: b\"]"}</rust.MacroCall>;
              </rust.FunctionDeclaration>

              <rust.FunctionDeclaration attributes="test" name={namekey("test_pop_all")}>
                <rust.LetDeclaration name={namekey("data")} mutable>
                  {"vec![1, 2, 3]"}
                </rust.LetDeclaration>
  
                <rust.MacroCall name="assert_eq">{"crate::client::pop_all(&mut data), vec![3, 2, 1]"}</rust.MacroCall>;
  
                <rust.MacroCall name="assert">{"data.is_empty()"}</rust.MacroCall>;
              </rust.FunctionDeclaration>

              <rust.FunctionDeclaration attributes="test" name={namekey("test_demo_macros")}>
                <rust.MacroCall name="assert_eq">{"crate::client::demo_macros(), \"count: 3\""}</rust.MacroCall>;
              </rust.FunctionDeclaration>
            </List>
          </rust.SourceFile>
        </rust.SourceDirectory>
      </rust.CrateDirectory>
    </Output>,
    { tabWidth: 4 },
  );
}

describe("rust-example output", () => {
  // ── Cargo.toml ──────────────────────────────────────────────────────
  it("generates the expected Cargo.toml", () => {
    const result = renderExample();
    const file = findFile(result, "Cargo.toml");
    expect(file).toBeDefined();
    const c = file.contents;

    expect(c).toContain('[package]');
    expect(c).toContain('name = "alloy-demo"');
    expect(c).toContain('version = "0.1.0"');
    expect(c).toContain('edition = "2024"');
    expect(c).toContain('[dependencies]');
    expect(c).not.toContain('serde');
    expect(c).toContain('tokio = { version = "1", features = ["rt", "macros"], optional = true }');
    expect(c).not.toContain('log');
    expect(c).not.toContain('[dev-dependencies]');
    expect(c).toContain('[features]');
    expect(c).toContain('async-runtime = ["dep:tokio"]');
  });

  // ── lib.rs ──────────────────────────────────────────────────────────
  it("generates the expected lib.rs content", () => {
    const result = renderExample();
    const file = findFile(result, "lib.rs");
    expect(file).toBeDefined();
    const c = file.contents;

    // Inner attribute
    expect(c).toContain("#![allow(dead_code)]");
    // Module doc comment
    expect(c).toContain("//! Alloy-generated demo crate");
    // Module declarations
    expect(c).toContain("pub mod models;");
    expect(c).toContain("pub mod traits;");
    expect(c).toContain("pub mod impls;");
    expect(c).toContain("pub mod client;");
    expect(c).toContain("pub mod utils;");
    expect(c).toContain("#[cfg(test)]");
    expect(c).toContain("mod tests;");
    // Re-exports
    expect(c).toContain("pub use crate::models::{Person, Status, Borrowed, Container}");
    expect(c).toContain("pub use crate::traits::{Greetable, AsyncFetchable}");
    expect(c).toContain("pub use crate::utils::AppResult");
  });

  // ── models.rs ───────────────────────────────────────────────────────
  it("generates the expected models.rs content", () => {
    const result = renderExample();
    const file = findFile(result, "models.rs");
    expect(file).toBeDefined();
    const c = file.contents;

    // Struct declarations
    expect(c).toContain("#[derive(Debug, Clone)]");
    expect(c).toContain("pub struct Person");
    expect(c).toContain("pub name: String");
    expect(c).toContain("pub age: u8");

    // Lifetime struct
    expect(c).toContain("pub struct Borrowed<'a>");
    expect(c).toContain("pub data: &'a str");

    // Container with pub(crate) field
    expect(c).toContain("pub struct Container");
    expect(c).toContain("pub(crate) metadata: String");

    // Enum with all variant types
    expect(c).toContain("pub enum Status");
    expect(c).toContain("Active");
    expect(c).toContain("Inactive(String)");
    expect(c).toContain("OnLeave {");
  });

  // ── traits.rs ───────────────────────────────────────────────────────
  it("generates the expected traits.rs content", () => {
    const result = renderExample();
    const file = findFile(result, "traits.rs");
    expect(file).toBeDefined();
    const c = file.contents;

    // Regular trait with default method
    expect(c).toContain("pub trait Greetable");
    expect(c).toContain("fn greet(&self) -> String");
    expect(c).toContain("fn greet_with_prefix(&self, prefix: &str) -> String");

    // Async trait
    // Edition 2024: native async fn in traits, no attributes needed
    expect(c).not.toContain("#[async_trait]");
    expect(c).toContain("#[allow(async_fn_in_trait)]");
    expect(c).toContain("pub trait AsyncFetchable");
    expect(c).toContain("async fn fetch(&self) -> Result<String, String>");

    // Cfg-conditional trait
    expect(c).toContain('#[cfg(feature = "async-runtime")]');
    expect(c).toContain("pub trait RuntimeAware");
  });

  // ── impls.rs ────────────────────────────────────────────────────────
  it("generates the expected impls.rs content", () => {
    const result = renderExample();
    const file = findFile(result, "impls.rs");
    expect(file).toBeDefined();
    const c = file.contents;

    // Impl block
    expect(c).toContain("impl Person");
    expect(c).toContain("pub fn new(name: String, age: u8) -> Person");

    // Match expression
    expect(c).toContain("match self.age");
    expect(c).toContain('0..=12 => "child"');

    // If/else expression
    expect(c).toContain("if self.age >= 18");

    // Member access / method chaining
    expect(c).toContain("self.name.chars().collect()");

    // Trait impl
    expect(c).toContain("impl Greetable for Person");

    // Turbofish
    expect(c).toContain("Vec::<String>::new()");
  });

  // ── client.rs ───────────────────────────────────────────────────────
  it("generates the expected client.rs content", () => {
    const result = renderExample();
    const file = findFile(result, "client.rs");
    expect(file).toBeDefined();
    const c = file.contents;

    // Error propagation with ?
    expect(c).toContain("parse::<usize>()?");

    // Closure
    expect(c).toContain(".map(|s| s.to_uppercase())");

    // Iterator-based format_all
    expect(c).toContain("pub fn format_all(");
    expect(c).toContain("-> Vec<String>");

    // While let loop returning values
    expect(c).toContain("while let Some(val) = data.pop()");
    expect(c).toContain("-> Vec<i32>");

    // Loop with label and break
    expect(c).toContain("'retry: loop");
    expect(c).toContain("break 'retry attempts");

    // If let expression
    expect(c).toContain("if let Some(name) = name_opt");

    // Macro invocations
    expect(c).toContain("vec![1, 2, 3]");
    expect(c).toContain("println!");
    expect(c).toContain("format!");
  });

  // ── utils.rs ────────────────────────────────────────────────────────
  it("generates the expected utils.rs content", () => {
    const result = renderExample();
    const file = findFile(result, "utils.rs");
    expect(file).toBeDefined();
    const c = file.contents;

    // Lifetime elision (no explicit lifetimes)
    expect(c).toContain("pub fn first_word(s: &str) -> &str");

    // Explicit lifetimes
    expect(c).toContain("pub fn longest<'a>(x: &'a str, y: &'a str) -> &'a str");

    // Tuple destructuring
    expect(c).toContain("let (x, y) = pair");

    // Struct destructuring
    expect(c).toContain("let crate::models::Person { name, age }");

    // macro_rules!
    expect(c).toContain("macro_rules! make_greeting");
    expect(c).toContain("#[macro_export]");

    // Constants and statics
    expect(c).toContain("pub const MAX_RETRIES: u32 = 5");
    expect(c).toContain("pub static DEFAULT_NAME: &str");

    // Error enum
    expect(c).toContain("pub enum AppError");
    expect(c).toContain("Parse(String)");
    expect(c).toContain("NotFound(String)");
    expect(c).toContain("Unknown(String)");
    expect(c).toContain("use std::error;");
    expect(c).toContain("use std::fmt;");
    expect(c).toContain("impl fmt::Display for AppError");
    expect(c).toContain("impl error::Error for AppError");

    // Type alias
    expect(c).toContain("pub type AppResult = Result<String, AppError>");
  });

  // ── tests.rs ────────────────────────────────────────────────────────
  it("generates the expected tests.rs content", () => {
    const result = renderExample();
    const file = findFile(result, "tests.rs");
    expect(file).toBeDefined();
    const c = file.contents;

    // Test functions are direct content (no extra mod tests wrapper)
    expect(c).not.toContain("#[cfg(test)]");
    expect(c).not.toContain("mod tests");

    // Test functions
    expect(c).toContain("#[test]");
    expect(c).toContain("fn test_person_new()");
    expect(c).toContain("fn test_describe_age()");
    expect(c).toContain("fn test_is_adult()");
    expect(c).toContain("fn test_swap_pair()");
    expect(c).toContain("fn test_first_word()");
    expect(c).toContain("fn test_parse_count()");
    expect(c).toContain("fn test_format_all()");
    expect(c).toContain("fn test_pop_all()");
    expect(c).toContain("fn test_demo_macros()");

    // Assert macros
    expect(c).toContain("assert_eq!");
    expect(c).toContain("assert!");
  });
});
