// Generated by scripts/generate-crate-descriptor.tsx
// Source: rustdoc JSON format version 57

import type { SymbolDescriptor } from "../../create-crate.js";

export const mod_clone = {
  Clone: {
    kind: "trait",
    metadata: {
      since: "1.0.0",
    },
  },
  CloneToUninit: {
    kind: "trait",
    metadata: {
      since: "unstable",
    },
  },
  TrivialClone: {
    kind: "trait",
    metadata: {
      since: "unstable",
    },
  },
  UseCloned: {
    kind: "trait",
    metadata: {
      since: "unstable",
    },
  },
} as const satisfies Record<string, SymbolDescriptor>;
