// Generated by scripts/generate-crate-descriptor.tsx
// Source: rustdoc JSON format version 57

import type { SymbolDescriptor } from "../../create-crate.js";

export const mod_contracts = {
  build_check_ensures: {
    kind: "function",
    metadata: {
      since: "unstable",
    },
  },
} as const satisfies Record<string, SymbolDescriptor>;
