// Generated by scripts/generate-crate-descriptor.tsx
// Source: rustdoc JSON format version 57

import type { SymbolDescriptor } from "../../create-crate.js";

export const mod_default_ = {
  Default: {
    kind: "trait",
    metadata: {
      since: "1.0.0",
    },
  },
} as const satisfies Record<string, SymbolDescriptor>;
