import {
  List,
  namekey,
  Output,
  render,
  writeOutput,
} from "@alloy-js/core";
import * as rust from "@alloy-js/rust";

// ── Refkeys for cross-referencing declarations ──────────────────────────────

const personRef = namekey("Person");
const borrowedRef = namekey("Borrowed");
const containerRef = namekey("Container");
const statusRef = namekey("Status");
const greetableRef = namekey("Greetable");
const asyncFetchableRef = namekey("AsyncFetchable");
const nameFieldRef = namekey("name");
const ageFieldRef = namekey("age");
const maxRetriesRef = namekey("MAX_RETRIES");
const defaultNameRef = namekey("DEFAULT_NAME");
const appResultRef = namekey("AppResult");

const output = render(
  <Output>
    <rust.CrateDirectory name="alloy-demo" edition="2024">
      {/* ── Cargo.toml ────────────────────────────────────────────── */}
      <rust.CargoToml
        version="0.1.0"
        authors={["Alloy Codegen <alloy@example.com>"]}
        description="A demo crate generated by alloy-js"
        license="MIT"
        dependencies={{
          tokio: { version: "1", features: ["rt", "macros"], optional: true },
        }}
        features={{
          "async-runtime": ["dep:tokio"],
          default: [],
        }}
      />

      <rust.SourceDirectory path="src">
        {/* ── lib.rs ──────────────────────────────────────────────── */}
        <rust.SourceFile
          path="lib.rs"
          header={<rust.InnerAttribute>allow(dead_code)</rust.InnerAttribute>}
          doc="Alloy-generated demo crate showcasing all features of @alloy-js/rust."
        >
          <rust.ModDeclaration name="models" visibility="pub" />
          <rust.ModDeclaration name="traits" visibility="pub" />
          <rust.ModDeclaration name="impls" visibility="pub" />
          <rust.ModDeclaration name="client" visibility="pub" />
          <rust.ModDeclaration name="utils" visibility="pub" />
          <>
            <rust.Cfg test />
            <rust.ModDeclaration name="tests" />
          </>

          <rust.PubUse path="crate::models" items={["Person", "Status", "Borrowed", "Container"]} />
          <rust.PubUse path="crate::traits" items={["Greetable", "AsyncFetchable"]} />
          <rust.PubUse path="crate::utils" items={["AppResult"]} />
        </rust.SourceFile>

        {/* ── models.rs ───────────────────────────────────────────── */}
        <rust.SourceFile path="models.rs" doc="Data models: structs with lifetimes, where clauses, enums.">
          {/* Person struct with Derive */}
          <>
            <rust.Derive traits={["Debug", "Clone"]} />
            <rust.StructDeclaration name={personRef} visibility="pub">
              <List>
                <rust.StructField name={nameFieldRef} type="String" visibility="pub" />
                <rust.StructField name={ageFieldRef} type="u8" visibility="pub" />
              </List>
            </rust.StructDeclaration>
          </>

          {/* Struct with lifetime parameter */}
          <>
            <rust.Derive traits={["Debug"]} />
            <rust.StructDeclaration name={borrowedRef} visibility="pub" lifetimes={["a"]}>
              <List>
                <rust.StructField
                  name={namekey("data")}
                  type={<rust.Ref lifetime="a">str</rust.Ref>}
                  visibility="pub"
                />
                <rust.StructField
                  name={namekey("label")}
                  type={<rust.Ref lifetime="a">str</rust.Ref>}
                  visibility="pub"
                />
              </List>
            </rust.StructDeclaration>
          </>

          {/* Struct with pub(crate) visibility on a field */}
          <>
            <rust.Derive traits={["Debug", "Clone"]} />
            <rust.StructDeclaration
              name={containerRef}
              visibility="pub"
            >
              <List>
                <rust.StructField name={namekey("value")} type="String" visibility="pub" />
                <rust.StructField
                  name={namekey("metadata")}
                  type="String"
                  visibility="pub(crate)"
                />
              </List>
            </rust.StructDeclaration>
          </>

          {/* Enum with all variant types */}
          <>
            <rust.Derive traits={["Debug"]} />
            <rust.EnumDeclaration name={statusRef} visibility="pub">
              <List>
                <rust.EnumVariant name={namekey("Active")} />
                <rust.TupleVariant name={namekey("Inactive")} types={["String"]} />
                <rust.StructVariant name={namekey("OnLeave")}>
                  <List>
                    <rust.StructField name={namekey("reason")} type="String" />
                    <rust.StructField name={namekey("days")} type="u32" />
                  </List>
                </rust.StructVariant>
              </List>
            </rust.EnumDeclaration>
          </>
        </rust.SourceFile>

        {/* ── traits.rs ───────────────────────────────────────────── */}
        <rust.SourceFile path="traits.rs" doc="Trait definitions: regular, async, and conditional.">
          {/* Regular trait with default method */}
          <rust.TraitDeclaration
            name={greetableRef}
            visibility="pub"
            doc="A trait for types that can produce a greeting."
          >
            <rust.TraitMethod name="greet" selfParam="&self" returns="String" />
            <rust.TraitMethod name="greet_with_prefix" selfParam="&self" parameters="prefix: &str" returns="String">
              <rust.MacroCall name="format">{'"{}: {}", prefix, self.greet()'}</rust.MacroCall>
            </rust.TraitMethod>
          </rust.TraitDeclaration>

          {/* Async trait */}
          <rust.TraitDeclaration
            name={asyncFetchableRef}
            visibility="pub"
            asyncTrait
            doc="An async trait for fetching data."
          >
            <rust.TraitMethod name="fetch" selfParam="&self" returns={<rust.Result ok="String" err="String" />} async />
          </rust.TraitDeclaration>

          {/* Conditional trait with #[cfg] */}
          <>
            <rust.Cfg feature="async-runtime" />
            <rust.TraitDeclaration name={namekey("RuntimeAware")} visibility="pub">
              <rust.TraitMethod name="runtime_name" selfParam="&self" returns={<rust.Ref>str</rust.Ref>} />
            </rust.TraitDeclaration>
          </>
        </rust.SourceFile>

        {/* ── impls.rs ────────────────────────────────────────────── */}
        <rust.SourceFile path="impls.rs" doc="Implementation blocks with match, if/else, member access, and turbofish.">
          {/* Impl block for Person */}
          <rust.ImplBlock type={personRef}>
            {/* Constructor */}
            <rust.FunctionDeclaration
              name={namekey("new")}
              visibility="pub"
              parameters={[
                { name: nameFieldRef, type: "String" },
                { name: ageFieldRef, type: "u8" },
              ]}
              returns={personRef}
            >
              <rust.StructExpression type={personRef}>
                <List>
                  <rust.StructFieldExpression name={nameFieldRef} />
                  <rust.StructFieldExpression name={ageFieldRef} />
                </List>
              </rust.StructExpression>
            </rust.FunctionDeclaration>

            {/* Method using match expression */}
            <rust.FunctionDeclaration
              name={namekey("describe_age")}
              visibility="pub"
              selfParam="&self"
              returns={<rust.Ref>str</rust.Ref>}
            >
              <rust.MatchExpression expr={<>self.{ageFieldRef}</>}>
                <rust.MatchArm pattern="0..=12">"child"</rust.MatchArm>
                <rust.MatchArm pattern="13..=19">"teenager"</rust.MatchArm>
                <rust.MatchArm pattern="20..=64">"adult"</rust.MatchArm>
                <rust.MatchArm pattern="_">"senior"</rust.MatchArm>
              </rust.MatchExpression>
            </rust.FunctionDeclaration>

            {/* Boolean expression */}
            <rust.FunctionDeclaration
              name={namekey("is_adult")}
              visibility="pub"
              selfParam="&self"
              returns="bool"
            >
              <rust.BinaryExpression left={<>self.{ageFieldRef}</>} op=">=" right="18" />
            </rust.FunctionDeclaration>

            {/* Method chaining via MemberExpression */}
            <rust.FunctionDeclaration
              name={namekey("name_chars")}
              visibility="pub"
              selfParam="&self"
              returns={<rust.Vec>char</rust.Vec>}
            >
              <rust.MemberExpression>
                <rust.MemberExpression.Property id="self" />
                <rust.MemberExpression.Property id={nameFieldRef} />
                <rust.MemberExpression.Method id="chars" args />
                <rust.MemberExpression.Method id="collect" args />
              </rust.MemberExpression>
            </rust.FunctionDeclaration>
          </rust.ImplBlock>

          {/* Trait impl for Person */}
          <rust.ImplBlock type={personRef} trait={greetableRef}>
            <rust.FunctionDeclaration
              name={namekey("greet")}
              selfParam="&self"
              returns="String"
            >
              <rust.MacroCall name="format">{"\"Hello, my name is {} and I am {} years old.\", self."}{nameFieldRef}{", self."}{ageFieldRef}</rust.MacroCall>
            </rust.FunctionDeclaration>
          </rust.ImplBlock>

          {/* Turbofish — used where type inference needs help */}
          <rust.FunctionDeclaration
            name={namekey("parse_number")}
            visibility="pub"
            parameters={[{ name: namekey("input"), type: "&str" }]}
            returns={<rust.Result ok="u8" err="String" />}
          >
            <rust.MemberExpression>
              <rust.MemberExpression.Property id="input" />
              <rust.MemberExpression.Method id="trim" args />
              <rust.MemberExpression.Method id="parse" args turbofish="u8" />
              <rust.MemberExpression.Method id="map_err" args={[
                <rust.ClosureExpression params={[{ name: "e" }]}>
                  <rust.FunctionCall name="to_string" receiver="e" args={[]} />
                </rust.ClosureExpression>
              ]} />
            </rust.MemberExpression>
          </rust.FunctionDeclaration>
        </rust.SourceFile>

        {/* ── client.rs ───────────────────────────────────────────── */}
        <rust.SourceFile path="client.rs" doc="Client functions: error handling, closures, loops, macro invocations.">
          {/* Function with ? error propagation */}
          <rust.FunctionDeclaration
            name={namekey("parse_count")}
            visibility="pub"
            parameters={[{ name: namekey("input"), type: "&str" }]}
            returns={<rust.Result ok="usize" err="std::num::ParseIntError" />}
          >
            <rust.LetDeclaration name={namekey("trimmed")}>
              <rust.MemberExpression>
                <rust.MemberExpression.Property id="input" />
                <rust.MemberExpression.Method id="trim" args />
              </rust.MemberExpression>
            </rust.LetDeclaration>
            <rust.LetDeclaration name={namekey("count")}>
              <rust.TryExpression>
                <rust.MemberExpression>
                  <rust.MemberExpression.Property id="trimmed" />
                  <rust.MemberExpression.Method id="parse" args turbofish="usize" />
                </rust.MemberExpression>
              </rust.TryExpression>
            </rust.LetDeclaration>
            Ok(count)
          </rust.FunctionDeclaration>

          {/* Closure passed to .map() */}
          <rust.FunctionDeclaration
            name={namekey("to_uppercase_all")}
            visibility="pub"
            parameters={[{ name: namekey("people"), type: "&[String]" }]}
            returns={<rust.Vec>String</rust.Vec>}
          >
            <rust.MemberExpression>
              <rust.MemberExpression.Property id="people" />
              <rust.MemberExpression.Method id="iter" args />
              <rust.MemberExpression.Method id="map" args={[
                <rust.ClosureExpression params={[{ name: "s" }]}>
                  <rust.FunctionCall name="to_uppercase" receiver="s" args={[]} />
                </rust.ClosureExpression>
              ]} />
              <rust.MemberExpression.Method id="collect" args />
            </rust.MemberExpression>
          </rust.FunctionDeclaration>

          {/* Iterator-based formatting returning Vec */}
          <rust.FunctionDeclaration
            name={namekey("format_all")}
            visibility="pub"
            parameters={[{ name: namekey("items"), type: "&[String]" }]}
            returns={<rust.Vec>String</rust.Vec>}
          >
            <rust.MemberExpression>
              <rust.MemberExpression.Property id="items" />
              <rust.MemberExpression.Method id="iter" args />
              <rust.MemberExpression.Method id="map" args={[
                <rust.ClosureExpression params={[{ name: "item" }]}>
                  <rust.MacroCall name="format">{"\"item: {}\", item"}</rust.MacroCall>
                </rust.ClosureExpression>
              ]} />
              <rust.MemberExpression.Method id="collect" args />
            </rust.MemberExpression>
          </rust.FunctionDeclaration>

          {/* While let loop for iterator draining, returning collected values */}
          <rust.FunctionDeclaration
            name={namekey("pop_all")}
            visibility="pub"
            parameters={[{ name: namekey("data"), type: "&mut Vec<i32>" }]}
            returns={<rust.Vec>i32</rust.Vec>}
          >
            <rust.LetDeclaration name={namekey("result")} mutable>
              {"Vec::new()"}
            </rust.LetDeclaration>
            <rust.WhileLetLoop pattern="Some(val)" expr="data.pop()">
              {"result.push(val);"}
            </rust.WhileLetLoop>
            result
          </rust.FunctionDeclaration>

          {/* Loop with break for retry logic */}
          <rust.FunctionDeclaration
            name={namekey("retry_until_success")}
            visibility="pub"
            returns="u32"
          >
            <rust.LetDeclaration name={namekey("attempts")} mutable>0u32</rust.LetDeclaration>
            <rust.Loop label="retry">
              <rust.AssignmentStatement target="attempts" op="+=">1</rust.AssignmentStatement>
              <rust.IfExpression condition={<rust.BinaryExpression left="attempts" op=">=" right="3" />}>
                {"break 'retry attempts;"}
              </rust.IfExpression>
            </rust.Loop>
          </rust.FunctionDeclaration>

          {/* if let expression */}
          <rust.FunctionDeclaration
            name={namekey("maybe_greet")}
            visibility="pub"
            parameters={[{ name: namekey("name_opt"), type: "Option<&str>" }]}
          >
            <rust.IfLetExpression pattern={<>Some(name)</>} expr="name_opt" else={<rust.MacroCall name="println">"no name provided"</rust.MacroCall>}>
              <rust.MacroCall name="println">{"\"hello, {}\", name"}</rust.MacroCall>
            </rust.IfLetExpression>
          </rust.FunctionDeclaration>

          {/* Macro invocations: vec![], format!() */}
          <rust.FunctionDeclaration
            name={namekey("demo_macros")}
            visibility="pub"
            returns="String"
          >
            <rust.LetDeclaration name={namekey("numbers")}><rust.MacroCall name="vec" delimiter={"["}>1, 2, 3</rust.MacroCall></rust.LetDeclaration>
            <rust.MacroCall name="format">{"\"count: {}\", numbers.len()"}</rust.MacroCall>
          </rust.FunctionDeclaration>
        </rust.SourceFile>

        {/* ── utils.rs ────────────────────────────────────────────── */}
        <rust.SourceFile path="utils.rs" doc="Utilities: lifetime elision, patterns, macros, constants, type aliases.">
          {/* Function where lifetime elision applies - single input ref */}
          <rust.FunctionDeclaration
            name={namekey("first_word")}
            visibility="pub"
            parameters={[{ name: namekey("s"), type: "&str" }]}
            returns="&str"
          >
            <rust.MemberExpression>
              <rust.MemberExpression.Property id="s" />
              <rust.MemberExpression.Method id="split_whitespace" args />
              <rust.MemberExpression.Method id="next" args />
              <rust.MemberExpression.Method id="unwrap_or" args={[<>""</>]} />
            </rust.MemberExpression>
          </rust.FunctionDeclaration>

          {/* Function where explicit lifetimes are required - multiple input refs */}
          <rust.FunctionDeclaration
            name={namekey("longest")}
            visibility="pub"
            lifetimes={["a"]}
            elideLifetimes={false}
            parameters={[
              { name: namekey("x"), type: "&'a str" },
              { name: namekey("y"), type: "&'a str" },
            ]}
            returns="&'a str"
          >
            <rust.IfExpression condition="x.len() >= y.len()" else="y">
              x
            </rust.IfExpression>
          </rust.FunctionDeclaration>

          {/* Tuple destructuring */}
          <rust.FunctionDeclaration
            name={namekey("swap_pair")}
            visibility="pub"
            parameters={[{ name: namekey("pair"), type: "(i32, i32)" }]}
            returns="(i32, i32)"
          >
            <rust.LetDeclaration pattern={<rust.TuplePattern>{["x", "y"]}</rust.TuplePattern>}>
              pair
            </rust.LetDeclaration>
            (y, x)
          </rust.FunctionDeclaration>

          {/* Direct field access instead of clone-then-destructure */}
          <rust.FunctionDeclaration
            name={namekey("describe_person")}
            visibility="pub"
            parameters={[{ name: namekey("person"), type: "&crate::models::Person" }]}
            returns="String"
          >
            <rust.MacroCall name="format">{"\"{} is {} years old\", person."}{nameFieldRef}{", person."}{ageFieldRef}</rust.MacroCall>
          </rust.FunctionDeclaration>

          {/* macro_rules! declaration */}
          <rust.MacroRules name="make_greeting" visibility="pub">
            {"($name:expr) => {\n    format!(\"Welcome, {}!\", $name)\n};"}
          </rust.MacroRules>

          {/* Constants */}
          <rust.ConstDeclaration name={maxRetriesRef} type="u32" visibility="pub">
            5
          </rust.ConstDeclaration>

          <rust.ConstDeclaration name={defaultNameRef} type="&str" visibility="pub">
            "Unknown"
          </rust.ConstDeclaration>

          {/* Error enum */}
          <>
            <rust.Derive traits={["Debug"]} />
            <rust.EnumDeclaration name={namekey("AppError")} visibility="pub">
              <List>
                <rust.TupleVariant name={namekey("Parse")} types={["String"]} />
                <rust.TupleVariant name={namekey("NotFound")} types={["String"]} />
                <rust.TupleVariant name={namekey("Unknown")} types={["String"]} />
              </List>
            </rust.EnumDeclaration>
          </>

          <rust.ImplBlock type="AppError" trait={rust.std.fmt.Display}>
            <rust.FunctionDeclaration
              name={namekey("fmt")}
              selfParam="&self"
              parameters={[{ name: namekey("f"), type: <>{rust.std.fmt.Formatter}{"<'_>"}</>, borrow: true, mut: true }]}
              returns={rust.std.fmt.Result}
            >
              <rust.MatchExpression expr="self">
                <rust.MatchArm pattern="AppError::Parse(msg)">
                  <rust.MacroCall name="write">{"f, \"parse error: {}\", msg"}</rust.MacroCall>
                </rust.MatchArm>
                <rust.MatchArm pattern="AppError::NotFound(msg)">
                  <rust.MacroCall name="write">{"f, \"not found: {}\", msg"}</rust.MacroCall>
                </rust.MatchArm>
                <rust.MatchArm pattern="AppError::Unknown(msg)">
                  <rust.MacroCall name="write">{"f, \"unknown error: {}\", msg"}</rust.MacroCall>
                </rust.MatchArm>
              </rust.MatchExpression>
            </rust.FunctionDeclaration>
          </rust.ImplBlock>

          <rust.ImplBlock type="AppError" trait={rust.std.error.Error} />

          {/* Type alias */}
          <rust.TypeAlias name={appResultRef} visibility="pub">
            {"Result<String, AppError>"}
          </rust.TypeAlias>
        </rust.SourceFile>

        {/* ── tests.rs ────────────────────────────────────────────── */}
        <rust.SourceFile path="tests.rs">
          <List doubleHardline>
            {/* Person constructor */}
            <rust.FunctionDeclaration attributes="test" name={namekey("test_person_new")}>
              <rust.LetDeclaration name={namekey("p")}>
                {"crate::models::Person::new(\"Alice\".to_string(), 30)"}
              </rust.LetDeclaration>
              <rust.MacroCall name="assert_eq">{"p.name, \"Alice\""}</rust.MacroCall>;
              <rust.MacroCall name="assert_eq">{"p.age, 30"}</rust.MacroCall>;
            </rust.FunctionDeclaration>

            {/* All match arms in describe_age */}
            <rust.FunctionDeclaration attributes="test" name={namekey("test_describe_age")}>
              <rust.MacroCall name="assert_eq">{"crate::models::Person::new(\"A\".to_string(), 10).describe_age(), \"child\""}</rust.MacroCall>;
              <rust.MacroCall name="assert_eq">{"crate::models::Person::new(\"A\".to_string(), 15).describe_age(), \"teenager\""}</rust.MacroCall>;
              <rust.MacroCall name="assert_eq">{"crate::models::Person::new(\"A\".to_string(), 30).describe_age(), \"adult\""}</rust.MacroCall>;
              <rust.MacroCall name="assert_eq">{"crate::models::Person::new(\"A\".to_string(), 70).describe_age(), \"senior\""}</rust.MacroCall>;
            </rust.FunctionDeclaration>

            {/* is_adult boundary */}
            <rust.FunctionDeclaration attributes="test" name={namekey("test_is_adult")}>
              <rust.MacroCall name="assert">{"!crate::models::Person::new(\"A\".to_string(), 17).is_adult()"}</rust.MacroCall>;
              <rust.MacroCall name="assert">{"crate::models::Person::new(\"A\".to_string(), 18).is_adult()"}</rust.MacroCall>;
            </rust.FunctionDeclaration>

            {/* name_chars */}
            <rust.FunctionDeclaration attributes="test" name={namekey("test_name_chars")}>
              <rust.LetDeclaration name={namekey("p")}>
                {"crate::models::Person::new(\"Hi\".to_string(), 1)"}
              </rust.LetDeclaration>
              <rust.MacroCall name="assert_eq">{"p.name_chars(), vec!['H', 'i']"}</rust.MacroCall>;
            </rust.FunctionDeclaration>

            {/* Greetable trait */}
            <rust.FunctionDeclaration attributes="test" name={namekey("test_greetable")}>
              {"use crate::traits::Greetable;"}
              <rust.LetDeclaration name={namekey("p")}>
                {"crate::models::Person::new(\"Alice\".to_string(), 30)"}
              </rust.LetDeclaration>
              <rust.MacroCall name="assert_eq">{"p.greet(), \"Hello, my name is Alice and I am 30 years old.\""}</rust.MacroCall>;
              <rust.MacroCall name="assert">{"p.greet_with_prefix(\"Note\").starts_with(\"Note: \")"}</rust.MacroCall>;
            </rust.FunctionDeclaration>

            {/* Status enum variants */}
            <rust.FunctionDeclaration attributes="test" name={namekey("test_status_enum")}>
              {"use crate::models::Status;"}
              <rust.MacroCall name="assert">{"matches!(Status::Active, Status::Active)"}</rust.MacroCall>;
              <rust.MacroCall name="assert">{"matches!(Status::Inactive(\"left\".to_string()), Status::Inactive(_))"}</rust.MacroCall>;
              <rust.MacroCall name="assert">{"matches!(Status::OnLeave { reason: \"vacation\".to_string(), days: 5 }, Status::OnLeave { days: 5, .. })"}</rust.MacroCall>;
            </rust.FunctionDeclaration>

            {/* Borrowed lifetime struct */}
            <rust.FunctionDeclaration attributes="test" name={namekey("test_borrowed_struct")}>
              <rust.LetDeclaration name={namekey("b")}>
                {"crate::models::Borrowed { data: \"hello\", label: \"test\" }"}
              </rust.LetDeclaration>
              <rust.MacroCall name="assert_eq">{"b.data, \"hello\""}</rust.MacroCall>;
              <rust.MacroCall name="assert_eq">{"b.label, \"test\""}</rust.MacroCall>;
            </rust.FunctionDeclaration>

            {/* Container with pub(crate) field */}
            <rust.FunctionDeclaration attributes="test" name={namekey("test_container")}>
              <rust.LetDeclaration name={namekey("c")}>
                {"crate::models::Container { value: \"pub\".to_string(), metadata: \"crate\".to_string() }"}
              </rust.LetDeclaration>
              <rust.MacroCall name="assert_eq">{"c.value, \"pub\""}</rust.MacroCall>;
              <rust.MacroCall name="assert_eq">{"c.metadata, \"crate\""}</rust.MacroCall>;
            </rust.FunctionDeclaration>

            {/* swap_pair */}
            <rust.FunctionDeclaration attributes="test" name={namekey("test_swap_pair")}>
              <rust.MacroCall name="assert_eq">{"crate::utils::swap_pair((1, 2)), (2, 1)"}</rust.MacroCall>;
            </rust.FunctionDeclaration>

            {/* first_word */}
            <rust.FunctionDeclaration attributes="test" name={namekey("test_first_word")}>
              <rust.MacroCall name="assert_eq">{"crate::utils::first_word(\"hello world\"), \"hello\""}</rust.MacroCall>;
              <rust.MacroCall name="assert_eq">{"crate::utils::first_word(\"\"), \"\""}</rust.MacroCall>;
            </rust.FunctionDeclaration>

            {/* longest */}
            <rust.FunctionDeclaration attributes="test" name={namekey("test_longest")}>
              <rust.MacroCall name="assert_eq">{"crate::utils::longest(\"hi\", \"hello\"), \"hello\""}</rust.MacroCall>;
              <rust.MacroCall name="assert_eq">{"crate::utils::longest(\"same\", \"size\"), \"same\""}</rust.MacroCall>;
            </rust.FunctionDeclaration>

            {/* describe_person */}
            <rust.FunctionDeclaration attributes="test" name={namekey("test_describe_person")}>
              <rust.LetDeclaration name={namekey("p")}>
                {"crate::models::Person::new(\"Bob\".to_string(), 25)"}
              </rust.LetDeclaration>
              <rust.MacroCall name="assert_eq">{"crate::utils::describe_person(&p), \"Bob is 25 years old\""}</rust.MacroCall>;
            </rust.FunctionDeclaration>

            {/* make_greeting macro */}
            <rust.FunctionDeclaration attributes="test" name={namekey("test_make_greeting")}>
              {"use crate::make_greeting;"}
              <rust.MacroCall name="assert_eq">{"make_greeting!(\"World\"), \"Welcome, World!\""}</rust.MacroCall>;
            </rust.FunctionDeclaration>

            {/* AppError display */}
            <rust.FunctionDeclaration attributes="test" name={namekey("test_app_error_display")}>
              <rust.MacroCall name="assert_eq">{"format!(\"{}\", crate::utils::AppError::Parse(\"bad\".to_string())), \"parse error: bad\""}</rust.MacroCall>;
              <rust.MacroCall name="assert_eq">{"format!(\"{}\", crate::utils::AppError::NotFound(\"missing\".to_string())), \"not found: missing\""}</rust.MacroCall>;
            </rust.FunctionDeclaration>

            {/* parse_count */}
            <rust.FunctionDeclaration attributes="test" name={namekey("test_parse_count")}>
              <rust.MacroCall name="assert_eq">{"crate::client::parse_count(\"  42  \").unwrap(), 42"}</rust.MacroCall>;
              <rust.MacroCall name="assert">{"crate::client::parse_count(\"abc\").is_err()"}</rust.MacroCall>;
            </rust.FunctionDeclaration>

            {/* to_uppercase_all */}
            <rust.FunctionDeclaration attributes="test" name={namekey("test_to_uppercase_all")}>
              <rust.LetDeclaration name={namekey("input")}>
                {"vec![\"hello\".to_string(), \"world\".to_string()]"}
              </rust.LetDeclaration>
              <rust.MacroCall name="assert_eq">{"crate::client::to_uppercase_all(&input), vec![\"HELLO\", \"WORLD\"]"}</rust.MacroCall>;
            </rust.FunctionDeclaration>

            {/* format_all */}
            <rust.FunctionDeclaration attributes="test" name={namekey("test_format_all")}>
              <rust.LetDeclaration name={namekey("input")}>
                {"vec![\"a\".to_string(), \"b\".to_string()]"}
              </rust.LetDeclaration>
              <rust.MacroCall name="assert_eq">{"crate::client::format_all(&input), vec![\"item: a\", \"item: b\"]"}</rust.MacroCall>;
            </rust.FunctionDeclaration>

            {/* pop_all */}
            <rust.FunctionDeclaration attributes="test" name={namekey("test_pop_all")}>
              <rust.LetDeclaration name={namekey("data")} mutable>
                {"vec![1, 2, 3]"}
              </rust.LetDeclaration>
              <rust.MacroCall name="assert_eq">{"crate::client::pop_all(&mut data), vec![3, 2, 1]"}</rust.MacroCall>;
              <rust.MacroCall name="assert">{"data.is_empty()"}</rust.MacroCall>;
            </rust.FunctionDeclaration>

            {/* retry_until_success */}
            <rust.FunctionDeclaration attributes="test" name={namekey("test_retry_until_success")}>
              <rust.MacroCall name="assert_eq">{"crate::client::retry_until_success(), 3"}</rust.MacroCall>;
            </rust.FunctionDeclaration>

            {/* demo_macros */}
            <rust.FunctionDeclaration attributes="test" name={namekey("test_demo_macros")}>
              <rust.MacroCall name="assert_eq">{"crate::client::demo_macros(), \"count: 3\""}</rust.MacroCall>;
            </rust.FunctionDeclaration>

            {/* parse_number */}
            <rust.FunctionDeclaration attributes="test" name={namekey("test_parse_number")}>
              <rust.MacroCall name="assert_eq">{"crate::impls::parse_number(\"42\").unwrap(), 42"}</rust.MacroCall>;
              <rust.MacroCall name="assert">{"crate::impls::parse_number(\"not a number\").is_err()"}</rust.MacroCall>;
            </rust.FunctionDeclaration>

            {/* Constants */}
            <rust.FunctionDeclaration attributes="test" name={namekey("test_constants")}>
              <rust.MacroCall name="assert_eq">{"crate::utils::MAX_RETRIES, 5"}</rust.MacroCall>;
              <rust.MacroCall name="assert_eq">{"crate::utils::DEFAULT_NAME, \"Unknown\""}</rust.MacroCall>;
            </rust.FunctionDeclaration>
          </List>
        </rust.SourceFile>
      </rust.SourceDirectory>
    </rust.CrateDirectory>
  </Output>,
  { tabWidth: 4 },
);

writeOutput(output, "./alloy-output");
