import {
  List,
  namekey,
  Output,
  render,
  writeOutput,
} from "@alloy-js/core";
import * as rust from "@alloy-js/rust";

// ── Refkeys for cross-referencing declarations ──────────────────────────────

const personRef = namekey("Person");
const borrowedRef = namekey("Borrowed");
const containerRef = namekey("Container");
const statusRef = namekey("Status");
const greetableRef = namekey("Greetable");
const asyncFetchableRef = namekey("AsyncFetchable");
const nameFieldRef = namekey("name");
const ageFieldRef = namekey("age");
const maxRetriesRef = namekey("MAX_RETRIES");
const defaultNameRef = namekey("DEFAULT_NAME");
const appResultRef = namekey("AppResult");

const output = render(
  <Output>
    <rust.CrateDirectory name="alloy-demo" edition="2024">
      {/* ── Cargo.toml ────────────────────────────────────────────── */}
      <rust.CargoToml
        name="alloy-demo"
        version="0.1.0"
        edition="2024"
        authors={["Alloy Codegen <alloy@example.com>"]}
        description="A demo crate generated by alloy-js"
        license="MIT"
        dependencies={{
          tokio: { version: "1", features: ["rt", "macros"], optional: true },
        }}
        features={{
          "async-runtime": ["dep:tokio"],
          default: [],
        }}
      />

      <rust.SourceDirectory path="src">
        {/* ── lib.rs ──────────────────────────────────────────────── */}
        <rust.SourceFile
          path="lib.rs"
          header={<rust.InnerAttribute>allow(dead_code)</rust.InnerAttribute>}
          doc="Alloy-generated demo crate showcasing all features of @alloy-js/rust."
        >
          <rust.ModDeclaration name="models" visibility="pub" />
          <rust.ModDeclaration name="traits" visibility="pub" />
          <rust.ModDeclaration name="impls" visibility="pub" />
          <rust.ModDeclaration name="client" visibility="pub" />
          <rust.ModDeclaration name="utils" visibility="pub" />
          <>
            <rust.Cfg test />
            <rust.ModDeclaration name="tests" />
          </>

          <rust.PubUse path="crate::models" items={["Person", "Status", "Borrowed", "Container"]} />
          <rust.PubUse path="crate::traits" items={["Greetable", "AsyncFetchable"]} />
          <rust.PubUse path="crate::utils" items={["AppResult"]} />
        </rust.SourceFile>

        {/* ── models.rs ───────────────────────────────────────────── */}
        <rust.SourceFile path="models.rs" doc="Data models: structs with lifetimes, where clauses, enums.">
          {/* Person struct with Derive */}
          <>
            <rust.Derive traits={["Debug", "Clone"]} />
            <rust.StructDeclaration name={personRef} visibility="pub">
              <List>
                <rust.StructField name={nameFieldRef} type="String" visibility="pub" />
                <rust.StructField name={ageFieldRef} type="i32" visibility="pub" />
              </List>
            </rust.StructDeclaration>
          </>

          {/* Struct with lifetime parameter */}
          <>
            <rust.Derive traits={["Debug"]} />
            <rust.StructDeclaration name={borrowedRef} visibility="pub" lifetimes={["a"]}>
              <List>
                <rust.StructField
                  name={namekey("data")}
                  type={<rust.Ref lifetime="a">str</rust.Ref>}
                  visibility="pub"
                />
                <rust.StructField
                  name={namekey("label")}
                  type={<rust.Ref lifetime="a">str</rust.Ref>}
                  visibility="pub"
                />
              </List>
            </rust.StructDeclaration>
          </>

          {/* Struct with pub(crate) visibility on a field */}
          <>
            <rust.Derive traits={["Debug", "Clone"]} />
            <rust.StructDeclaration
              name={containerRef}
              visibility="pub"
            >
              <List>
                <rust.StructField name={namekey("value")} type="String" visibility="pub" />
                <rust.StructField
                  name={namekey("metadata")}
                  type="String"
                  visibility="pub(crate)"
                />
              </List>
            </rust.StructDeclaration>
          </>

          {/* Enum with all variant types */}
          <>
            <rust.Derive traits={["Debug"]} />
            <rust.EnumDeclaration name={statusRef} visibility="pub">
              <List>
                <rust.EnumVariant name={namekey("Active")} />
                <rust.TupleVariant name={namekey("Inactive")} types={["String"]} />
                <rust.StructVariant name={namekey("OnLeave")}>
                  <List>
                    <rust.StructField name={namekey("reason")} type="String" />
                    <rust.StructField name={namekey("days")} type="u32" />
                  </List>
                </rust.StructVariant>
              </List>
            </rust.EnumDeclaration>
          </>
        </rust.SourceFile>

        {/* ── traits.rs ───────────────────────────────────────────── */}
        <rust.SourceFile path="traits.rs" doc="Trait definitions: regular, async, and conditional.">
          {/* Regular trait with default method */}
          <rust.TraitDeclaration
            name={greetableRef}
            visibility="pub"
            doc="A trait for types that can produce a greeting."
          >
            <rust.TraitMethod name="greet" selfParam="&self" returns="String" />
            <rust.TraitMethod name="greet_with_prefix" selfParam="&self" parameters="prefix: &str" returns="String">
              <rust.MacroCall name="format">{'"{}: {}", prefix, self.greet()'}</rust.MacroCall>
            </rust.TraitMethod>
          </rust.TraitDeclaration>

          {/* Async trait */}
          <rust.TraitDeclaration
            name={asyncFetchableRef}
            visibility="pub"
            asyncTrait
            doc="An async trait for fetching data."
          >
            <rust.TraitMethod name="fetch" selfParam="&self" returns={<rust.Result ok="String" err="String" />} async />
          </rust.TraitDeclaration>

          {/* Conditional trait with #[cfg] */}
          <>
            <rust.Cfg feature="async-runtime" />
            <rust.TraitDeclaration name={namekey("RuntimeAware")} visibility="pub">
              <rust.TraitMethod name="runtime_name" selfParam="&self" returns={<rust.Ref>str</rust.Ref>} />
            </rust.TraitDeclaration>
          </>
        </rust.SourceFile>

        {/* ── impls.rs ────────────────────────────────────────────── */}
        <rust.SourceFile path="impls.rs" doc="Implementation blocks with match, if/else, member access, and turbofish.">
          {/* Impl block for Person */}
          <rust.ImplBlock type={personRef}>
            {/* Constructor */}
            <rust.FunctionDeclaration
              name={namekey("new")}
              visibility="pub"
              parameters={[
                { name: nameFieldRef, type: "String" },
                { name: ageFieldRef, type: "i32" },
              ]}
              returns={personRef}
            >
              <rust.StructExpression type={personRef}>
                <List>
                  <rust.StructFieldExpression name={nameFieldRef} />
                  <rust.StructFieldExpression name={ageFieldRef} />
                </List>
              </rust.StructExpression>
            </rust.FunctionDeclaration>

            {/* Method using match expression */}
            <rust.FunctionDeclaration
              name={namekey("describe_age")}
              visibility="pub"
              selfParam="&self"
              returns={<rust.Ref>str</rust.Ref>}
            >
              <rust.MatchExpression expr={<>self.{ageFieldRef}</>}>
                <rust.MatchArm pattern="0..=12">"child"</rust.MatchArm>
                <rust.MatchArm pattern="13..=19">"teenager"</rust.MatchArm>
                <rust.MatchArm pattern="20..=64">"adult"</rust.MatchArm>
                <rust.MatchArm pattern="_">"senior"</rust.MatchArm>
              </rust.MatchExpression>
            </rust.FunctionDeclaration>

            {/* Boolean expression */}
            <rust.FunctionDeclaration
              name={namekey("is_adult")}
              visibility="pub"
              selfParam="&self"
              returns="bool"
            >
              <rust.BinaryExpression left={<>self.{ageFieldRef}</>} op=">=" right="18" />
            </rust.FunctionDeclaration>

            {/* Method chaining via MemberExpression */}
            <rust.FunctionDeclaration
              name={namekey("name_chars")}
              visibility="pub"
              selfParam="&self"
              returns={<rust.Vec>char</rust.Vec>}
            >
              <rust.MemberExpression>
                <rust.MemberExpression.Part id="self" />
                <rust.MemberExpression.Part id={nameFieldRef} />
                <rust.MemberExpression.Part id="chars" args={[]} />
                <rust.MemberExpression.Part id="collect" args={[]} />
              </rust.MemberExpression>
            </rust.FunctionDeclaration>
          </rust.ImplBlock>

          {/* Trait impl for Person */}
          <rust.ImplBlock type={personRef} trait={greetableRef}>
            <rust.FunctionDeclaration
              name={namekey("greet")}
              selfParam="&self"
              returns="String"
            >
              <rust.MacroCall name="format">{"\"Hello, my name is {} and I am {} years old.\", self."}{nameFieldRef}{", self."}{ageFieldRef}</rust.MacroCall>
            </rust.FunctionDeclaration>
          </rust.ImplBlock>

          {/* Turbofish — used where type inference needs help */}
          <rust.FunctionDeclaration
            name={namekey("parse_number")}
            visibility="pub"
            parameters={[{ name: namekey("input"), type: "&str" }]}
            returns={<rust.Result ok="i32" err="String" />}
          >
            <rust.MemberExpression>
              <rust.MemberExpression.Part id="input" />
              <rust.MemberExpression.Part id="trim" args={[]} />
              <rust.MemberExpression.Part id="parse" args={[]} turbofish="i32" />
              <rust.MemberExpression.Part id="map_err" args={[
                <rust.ClosureExpression params={[{ name: "e" }]}>
                  <rust.FunctionCall name="to_string" receiver="e" args={[]} />
                </rust.ClosureExpression>
              ]} />
            </rust.MemberExpression>
          </rust.FunctionDeclaration>
        </rust.SourceFile>

        {/* ── client.rs ───────────────────────────────────────────── */}
        <rust.SourceFile path="client.rs" doc="Client functions: error handling, closures, loops, macro invocations.">
          {/* Function with ? error propagation */}
          <rust.FunctionDeclaration
            name={namekey("parse_count")}
            visibility="pub"
            parameters={[{ name: namekey("input"), type: "&str" }]}
            returns={<rust.Result ok="usize" err="std::num::ParseIntError" />}
          >
            <rust.LetDeclaration name={namekey("trimmed")}>
              <rust.MemberExpression>
                <rust.MemberExpression.Part id="input" />
                <rust.MemberExpression.Part id="trim" args={[]} />
              </rust.MemberExpression>
            </rust.LetDeclaration>
            <hbr />
            <rust.LetDeclaration name={namekey("count")}>
              <rust.TryExpression>
                <rust.MemberExpression>
                  <rust.MemberExpression.Part id="trimmed" />
                  <rust.MemberExpression.Part id="parse" args={[]} turbofish="usize" />
                </rust.MemberExpression>
              </rust.TryExpression>
            </rust.LetDeclaration>
            <hbr />
            Ok(count)
          </rust.FunctionDeclaration>

          {/* Closure passed to .map() */}
          <rust.FunctionDeclaration
            name={namekey("to_uppercase_all")}
            visibility="pub"
            parameters={[{ name: namekey("people"), type: "&[String]" }]}
            returns={<rust.Vec>String</rust.Vec>}
          >
            <rust.MemberExpression>
              <rust.MemberExpression.Part id="people" />
              <rust.MemberExpression.Part id="iter" args={[]} />
              <rust.MemberExpression.Part id="map" args={[
                <rust.ClosureExpression params={[{ name: "s" }]}>
                  <rust.FunctionCall name="to_uppercase" receiver="s" args={[]} />
                </rust.ClosureExpression>
              ]} />
              <rust.MemberExpression.Part id="collect" args={[]} />
            </rust.MemberExpression>
          </rust.FunctionDeclaration>

          {/* For loop over collection */}
          <rust.FunctionDeclaration
            name={namekey("print_all")}
            visibility="pub"
            parameters={[{ name: namekey("items"), type: "&[String]" }]}
          >
            <rust.ForLoop pattern="item" iter="items">
              <rust.MacroCall name="println">{"\"item: {}\", item"}</rust.MacroCall>
            </rust.ForLoop>
          </rust.FunctionDeclaration>

          {/* While let loop for iterator draining */}
          <rust.FunctionDeclaration
            name={namekey("pop_all")}
            visibility="pub"
            parameters={[{ name: namekey("data"), type: "&mut Vec<i32>" }]}
          >
            <rust.WhileLetLoop pattern="Some(val)" expr="data.pop()">
              <rust.MacroCall name="println">{"\"popped: {}\", val"}</rust.MacroCall>
            </rust.WhileLetLoop>
          </rust.FunctionDeclaration>

          {/* Loop with break for retry logic */}
          <rust.FunctionDeclaration
            name={namekey("retry_until_success")}
            visibility="pub"
            returns="u32"
          >
            <rust.LetDeclaration name={namekey("attempts")} mutable>0u32</rust.LetDeclaration>
            <hbr />
            <rust.Loop label="retry">
              <rust.AssignmentStatement target="attempts" op="+=">1</rust.AssignmentStatement>
              <hbr />
              <rust.IfExpression condition={<rust.BinaryExpression left="attempts" op=">=" right="3" />}>
                {"break 'retry attempts;"}
              </rust.IfExpression>
            </rust.Loop>
          </rust.FunctionDeclaration>

          {/* if let expression */}
          <rust.FunctionDeclaration
            name={namekey("maybe_greet")}
            visibility="pub"
            parameters={[{ name: namekey("name_opt"), type: "Option<&str>" }]}
          >
            <rust.IfLetExpression pattern={<>Some(name)</>} expr="name_opt" else={<rust.MacroCall name="println">"no name provided"</rust.MacroCall>}>
              <rust.MacroCall name="println">{"\"hello, {}\", name"}</rust.MacroCall>
            </rust.IfLetExpression>
          </rust.FunctionDeclaration>

          {/* Macro invocations: vec![], format!() */}
          <rust.FunctionDeclaration
            name={namekey("demo_macros")}
            visibility="pub"
            returns="String"
          >
            <rust.LetDeclaration name={namekey("numbers")}><rust.MacroCall name="vec" delimiter={"["}>1, 2, 3</rust.MacroCall></rust.LetDeclaration>
            <hbr />
            <rust.MacroCall name="format">{"\"count: {}\", numbers.len()"}</rust.MacroCall>
          </rust.FunctionDeclaration>
        </rust.SourceFile>

        {/* ── utils.rs ────────────────────────────────────────────── */}
        <rust.SourceFile path="utils.rs" doc="Utilities: lifetime elision, patterns, macros, constants, type aliases.">
          {/* Function where lifetime elision applies - single input ref */}
          <rust.FunctionDeclaration
            name={namekey("first_word")}
            visibility="pub"
            parameters={[{ name: namekey("s"), type: "&str" }]}
            returns="&str"
          >
            <rust.MemberExpression>
              <rust.MemberExpression.Part id="s" />
              <rust.MemberExpression.Part id="split_whitespace" args={[]} />
              <rust.MemberExpression.Part id="next" args={[]} />
              <rust.MemberExpression.Part id="unwrap_or" args={[<>""</>]} />
            </rust.MemberExpression>
          </rust.FunctionDeclaration>

          {/* Function where explicit lifetimes are required - multiple input refs */}
          <rust.FunctionDeclaration
            name={namekey("longest")}
            visibility="pub"
            lifetimes={["a"]}
            elideLifetimes={false}
            parameters={[
              { name: namekey("x"), type: "&'a str" },
              { name: namekey("y"), type: "&'a str" },
            ]}
            returns="&'a str"
          >
            <rust.IfExpression condition="x.len() >= y.len()" else="y">
              x
            </rust.IfExpression>
          </rust.FunctionDeclaration>

          {/* Tuple destructuring */}
          <rust.FunctionDeclaration
            name={namekey("swap_pair")}
            visibility="pub"
            parameters={[{ name: namekey("pair"), type: "(i32, i32)" }]}
            returns="(i32, i32)"
          >
            <rust.LetDeclaration pattern={<rust.TuplePattern>{["x", "y"]}</rust.TuplePattern>}>
              pair
            </rust.LetDeclaration>
            <hbr />
            (y, x)
          </rust.FunctionDeclaration>

          {/* Direct field access instead of clone-then-destructure */}
          <rust.FunctionDeclaration
            name={namekey("describe_person")}
            visibility="pub"
            parameters={[{ name: namekey("person"), type: "&crate::models::Person" }]}
            returns="String"
          >
            <rust.MacroCall name="format">{"\"{} is {} years old\", person."}{nameFieldRef}{", person."}{ageFieldRef}</rust.MacroCall>
          </rust.FunctionDeclaration>

          {/* macro_rules! declaration */}
          <rust.MacroRules name="make_greeting" visibility="pub">
            {"($name:expr) => {\n    format!(\"Welcome, {}!\", $name)\n};"}
          </rust.MacroRules>

          {/* Constants */}
          <rust.ConstDeclaration name={maxRetriesRef} type="u32" visibility="pub">
            5
          </rust.ConstDeclaration>

          <rust.ConstDeclaration name={defaultNameRef} type="&str" visibility="pub">
            "Unknown"
          </rust.ConstDeclaration>

          {/* Error enum */}
          <>
            <rust.Derive traits={["Debug"]} />
            <rust.EnumDeclaration name={namekey("AppError")} visibility="pub">
              <List>
                <rust.TupleVariant name={namekey("Parse")} types={["String"]} />
                <rust.TupleVariant name={namekey("NotFound")} types={["String"]} />
                <rust.TupleVariant name={namekey("Unknown")} types={["String"]} />
              </List>
            </rust.EnumDeclaration>
          </>

          <rust.ImplBlock type="AppError" trait="std::fmt::Display">
            <rust.FunctionDeclaration
              name={namekey("fmt")}
              selfParam="&self"
              parameters={[{ name: namekey("f"), type: "&mut std::fmt::Formatter<'_>" }]}
              returns="std::fmt::Result"
            >
              <rust.MatchExpression expr="self">
                <rust.MatchArm pattern="AppError::Parse(msg)">
                  <rust.MacroCall name="write">{"f, \"parse error: {}\", msg"}</rust.MacroCall>
                </rust.MatchArm>
                <rust.MatchArm pattern="AppError::NotFound(msg)">
                  <rust.MacroCall name="write">{"f, \"not found: {}\", msg"}</rust.MacroCall>
                </rust.MatchArm>
                <rust.MatchArm pattern="AppError::Unknown(msg)">
                  <rust.MacroCall name="write">{"f, \"unknown error: {}\", msg"}</rust.MacroCall>
                </rust.MatchArm>
              </rust.MatchExpression>
            </rust.FunctionDeclaration>
          </rust.ImplBlock>

          <rust.ImplBlock type="AppError" trait="std::error::Error" />

          {/* Type alias */}
          <rust.TypeAlias name={appResultRef} visibility="pub">
            {"Result<String, AppError>"}
          </rust.TypeAlias>
        </rust.SourceFile>

        {/* ── tests.rs ────────────────────────────────────────────── */}
        <rust.SourceFile path="tests.rs">
          <rust.TestModule>
            <List doubleHardline>
              <rust.FunctionDeclaration attributes="test" name={namekey("test_person_new")}>
                <rust.LetDeclaration name={namekey("p")}>
                  {"crate::models::Person::new(\"Alice\".to_string(), 30)"}
                </rust.LetDeclaration>
                <hbr />
                <rust.MacroCall name="assert_eq">{"p.name, \"Alice\""}</rust.MacroCall>;
                <hbr />
                <rust.MacroCall name="assert_eq">{"p.age, 30"}</rust.MacroCall>;
              </rust.FunctionDeclaration>

              <rust.FunctionDeclaration attributes="test" name={namekey("test_describe_age")}>
                <rust.LetDeclaration name={namekey("child")}>
                  {"crate::models::Person::new(\"Bob\".to_string(), 10)"}
                </rust.LetDeclaration>
                <hbr />
                <rust.MacroCall name="assert_eq">{'child.describe_age(), "child"'}</rust.MacroCall>;
              </rust.FunctionDeclaration>

              <rust.FunctionDeclaration attributes="test" name={namekey("test_swap_pair")}>
                <rust.LetDeclaration name={namekey("result")}>
                  crate::utils::swap_pair((1, 2))
                </rust.LetDeclaration>
                <hbr />
                <rust.MacroCall name="assert_eq">{"result, (2, 1)"}</rust.MacroCall>;
              </rust.FunctionDeclaration>
            </List>
          </rust.TestModule>
        </rust.SourceFile>
      </rust.SourceDirectory>
    </rust.CrateDirectory>
  </Output>,
  { tabWidth: 4 },
);

writeOutput(output, "./alloy-output");
