// Generated by scripts/generate-crate-descriptor.tsx
// Source: rustdoc JSON format version 57

import type { SymbolDescriptor } from "../../create-crate.js";

export const mod_cmp = {
  Eq: {
    kind: "trait",
    canonicalCrate: "core",
  },
  max: {
    kind: "function",
    canonicalCrate: "core",
    metadata: {
      since: "1.0.0",
    },
  },
  max_by: {
    kind: "function",
    canonicalCrate: "core",
    metadata: {
      since: "1.53.0",
    },
  },
  max_by_key: {
    kind: "function",
    canonicalCrate: "core",
    metadata: {
      since: "1.53.0",
    },
  },
  min: {
    kind: "function",
    canonicalCrate: "core",
  },
  min_by: {
    kind: "function",
    canonicalCrate: "core",
    metadata: {
      since: "1.53.0",
    },
  },
  min_by_key: {
    kind: "function",
    canonicalCrate: "core",
    metadata: {
      since: "1.53.0",
    },
  },
  minmax: {
    kind: "function",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
  },
  minmax_by: {
    kind: "function",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
  },
  minmax_by_key: {
    kind: "function",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
  },
  Ord: {
    kind: "trait",
    canonicalCrate: "core",
  },
  Ordering: {
    kind: "enum",
    canonicalCrate: "core",
    members: {
      Equal: {
        kind: "variant",
        shape: "unit",
        metadata: {
          since: "1.0.0",
        },
      },
      Greater: {
        kind: "variant",
        shape: "unit",
        metadata: {
          since: "1.0.0",
        },
      },
      is_eq: {
        kind: "function",
        metadata: {
          since: "1.53.0",
        },
      },
      is_ge: {
        kind: "function",
        metadata: {
          since: "1.53.0",
        },
      },
      is_gt: {
        kind: "function",
        metadata: {
          since: "1.53.0",
        },
      },
      is_le: {
        kind: "function",
        metadata: {
          since: "1.53.0",
        },
      },
      is_lt: {
        kind: "function",
        metadata: {
          since: "1.53.0",
        },
      },
      is_ne: {
        kind: "function",
        metadata: {
          since: "1.53.0",
        },
      },
      Less: {
        kind: "variant",
        shape: "unit",
        metadata: {
          since: "1.0.0",
        },
      },
      reverse: {
        kind: "function",
        metadata: {
          since: "1.48.0",
        },
      },
      then: {
        kind: "function",
        metadata: {
          since: "1.48.0",
        },
      },
      then_with: {
        kind: "function",
        metadata: {
          since: "1.17.0",
        },
      },
    },
  },
  PartialEq: {
    kind: "trait",
    canonicalCrate: "core",
  },
  PartialOrd: {
    kind: "trait",
    canonicalCrate: "core",
  },
  Reverse: {
    kind: "struct",
    canonicalCrate: "core",
  },
} as const satisfies Record<string, SymbolDescriptor>;
