// Generated by scripts/generate-crate-descriptor.tsx
// Source: rustdoc JSON format version 57

import type { SymbolDescriptor } from "../../create-crate.js";

export const mod_error = {
  Error: {
    kind: "trait",
    canonicalCrate: "core",
  },
  Report: {
    kind: "struct",
    metadata: {
      since: "unstable",
    },
    members: {
      new: {
        kind: "function",
        associated: true,
        metadata: {
          since: "unstable",
        },
      },
      pretty: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      show_backtrace: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
    },
  },
  Request: {
    kind: "struct",
    canonicalCrate: "core",
    members: {
      provide_ref: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      provide_ref_with: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      provide_value: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      provide_value_with: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      would_be_satisfied_by_ref_of: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      would_be_satisfied_by_value_of: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
    },
  },
  request_ref: {
    kind: "function",
    canonicalCrate: "core",
  },
  request_value: {
    kind: "function",
    canonicalCrate: "core",
  },
  Source: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
  },
} as const satisfies Record<string, SymbolDescriptor>;
