// Generated by scripts/generate-crate-descriptor.tsx
// Source: rustdoc JSON format version 57

import type { SymbolDescriptor } from "../../create-crate.js";

export const mod_ffi = {
  c_char: {
    kind: "type-alias",
    canonicalCrate: "core",
  },
  c_double: {
    kind: "type-alias",
    canonicalCrate: "core",
  },
  c_float: {
    kind: "type-alias",
    canonicalCrate: "core",
  },
  c_int: {
    kind: "type-alias",
    canonicalCrate: "core",
  },
  c_long: {
    kind: "type-alias",
    canonicalCrate: "core",
  },
  c_longlong: {
    kind: "type-alias",
    canonicalCrate: "core",
  },
  c_ptrdiff_t: {
    kind: "type-alias",
    canonicalCrate: "core",
  },
  c_schar: {
    kind: "type-alias",
    canonicalCrate: "core",
  },
  c_short: {
    kind: "type-alias",
    canonicalCrate: "core",
  },
  c_size_t: {
    kind: "type-alias",
    canonicalCrate: "core",
  },
  c_ssize_t: {
    kind: "type-alias",
    canonicalCrate: "core",
  },
  c_uchar: {
    kind: "type-alias",
    canonicalCrate: "core",
  },
  c_uint: {
    kind: "type-alias",
    canonicalCrate: "core",
  },
  c_ulong: {
    kind: "type-alias",
    canonicalCrate: "core",
  },
  c_ulonglong: {
    kind: "type-alias",
    canonicalCrate: "core",
  },
  c_ushort: {
    kind: "type-alias",
    canonicalCrate: "core",
  },
  c_void: {
    kind: "enum",
    canonicalCrate: "core",
  },
  CStr: {
    kind: "struct",
    canonicalCrate: "core",
    members: {
      as_c_str: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      as_ptr: {
        kind: "function",
        metadata: {
          since: "1.0.0",
        },
      },
      bytes: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      count_bytes: {
        kind: "function",
        metadata: {
          since: "1.79.0",
        },
      },
      display: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      from_bytes_until_nul: {
        kind: "function",
        associated: true,
        metadata: {
          since: "1.69.0",
        },
      },
      from_bytes_with_nul: {
        kind: "function",
        associated: true,
        metadata: {
          since: "1.10.0",
        },
      },
      from_bytes_with_nul_unchecked: {
        kind: "function",
        associated: true,
        metadata: {
          since: "1.10.0",
        },
      },
      from_ptr: {
        kind: "function",
        associated: true,
        metadata: {
          since: "1.0.0",
        },
      },
      is_empty: {
        kind: "function",
        metadata: {
          since: "1.71.0",
        },
      },
      to_bytes: {
        kind: "function",
        metadata: {
          since: "1.0.0",
        },
      },
      to_bytes_with_nul: {
        kind: "function",
        metadata: {
          since: "1.0.0",
        },
      },
      to_str: {
        kind: "function",
        metadata: {
          since: "1.4.0",
        },
      },
    },
  },
  CString: {
    kind: "struct",
    canonicalCrate: "alloc",
    members: {
      as_bytes: {
        kind: "function",
        metadata: {
          since: "1.0.0",
        },
      },
      as_bytes_with_nul: {
        kind: "function",
        metadata: {
          since: "1.0.0",
        },
      },
      as_c_str: {
        kind: "function",
        metadata: {
          since: "1.20.0",
        },
      },
      from_raw: {
        kind: "function",
        associated: true,
        metadata: {
          since: "1.4.0",
        },
      },
      from_vec_unchecked: {
        kind: "function",
        associated: true,
        metadata: {
          since: "1.0.0",
        },
      },
      from_vec_with_nul: {
        kind: "function",
        associated: true,
        metadata: {
          since: "1.58.0",
        },
      },
      from_vec_with_nul_unchecked: {
        kind: "function",
        associated: true,
        metadata: {
          since: "1.58.0",
        },
      },
      into_boxed_c_str: {
        kind: "function",
        metadata: {
          since: "1.20.0",
        },
      },
      into_bytes: {
        kind: "function",
        metadata: {
          since: "1.7.0",
        },
      },
      into_bytes_with_nul: {
        kind: "function",
        metadata: {
          since: "1.7.0",
        },
      },
      into_raw: {
        kind: "function",
        metadata: {
          since: "1.4.0",
        },
      },
      into_string: {
        kind: "function",
        metadata: {
          since: "1.7.0",
        },
      },
      new: {
        kind: "function",
        associated: true,
        metadata: {
          since: "1.0.0",
        },
      },
    },
  },
  FromBytesUntilNulError: {
    kind: "struct",
    canonicalCrate: "core",
  },
  FromBytesWithNulError: {
    kind: "enum",
    canonicalCrate: "core",
    members: {
      InteriorNul: {
        kind: "variant",
        shape: "struct",
      },
      NotNulTerminated: {
        kind: "variant",
        shape: "unit",
      },
    },
  },
  FromVecWithNulError: {
    kind: "struct",
    canonicalCrate: "alloc",
    members: {
      as_bytes: {
        kind: "function",
        metadata: {
          since: "1.58.0",
        },
      },
      into_bytes: {
        kind: "function",
        metadata: {
          since: "1.58.0",
        },
      },
    },
  },
  IntoStringError: {
    kind: "struct",
    canonicalCrate: "alloc",
    members: {
      into_cstring: {
        kind: "function",
        metadata: {
          since: "1.7.0",
        },
      },
      utf8_error: {
        kind: "function",
        metadata: {
          since: "1.7.0",
        },
      },
    },
  },
  NulError: {
    kind: "struct",
    canonicalCrate: "alloc",
    members: {
      into_vec: {
        kind: "function",
        metadata: {
          since: "1.0.0",
        },
      },
      nul_position: {
        kind: "function",
        metadata: {
          since: "1.0.0",
        },
      },
    },
  },
  OsStr: {
    kind: "struct",
    metadata: {
      since: "1.0.0",
    },
    members: {
      as_encoded_bytes: {
        kind: "function",
        metadata: {
          since: "1.74.0",
        },
      },
      as_os_str: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      display: {
        kind: "function",
        metadata: {
          since: "1.87.0",
        },
      },
      eq_ignore_ascii_case: {
        kind: "function",
        metadata: {
          since: "1.53.0",
        },
      },
      from_encoded_bytes_unchecked: {
        kind: "function",
        associated: true,
        metadata: {
          since: "1.74.0",
        },
      },
      into_os_string: {
        kind: "function",
        metadata: {
          since: "1.20.0",
        },
      },
      is_ascii: {
        kind: "function",
        metadata: {
          since: "1.53.0",
        },
      },
      is_empty: {
        kind: "function",
        metadata: {
          since: "1.9.0",
        },
      },
      len: {
        kind: "function",
        metadata: {
          since: "1.9.0",
        },
      },
      make_ascii_lowercase: {
        kind: "function",
        metadata: {
          since: "1.53.0",
        },
      },
      make_ascii_uppercase: {
        kind: "function",
        metadata: {
          since: "1.53.0",
        },
      },
      new: {
        kind: "function",
        associated: true,
        metadata: {
          since: "1.0.0",
        },
      },
      slice_encoded_bytes: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      to_ascii_lowercase: {
        kind: "function",
        metadata: {
          since: "1.53.0",
        },
      },
      to_ascii_uppercase: {
        kind: "function",
        metadata: {
          since: "1.53.0",
        },
      },
      to_os_string: {
        kind: "function",
        metadata: {
          since: "1.0.0",
        },
      },
      to_str: {
        kind: "function",
        metadata: {
          since: "1.0.0",
        },
      },
      to_string_lossy: {
        kind: "function",
        metadata: {
          since: "1.0.0",
        },
      },
    },
  },
  OsString: {
    kind: "struct",
    metadata: {
      since: "1.0.0",
    },
    members: {
      as_os_str: {
        kind: "function",
        metadata: {
          since: "1.0.0",
        },
      },
      capacity: {
        kind: "function",
        metadata: {
          since: "1.9.0",
        },
      },
      clear: {
        kind: "function",
        metadata: {
          since: "1.9.0",
        },
      },
      from_encoded_bytes_unchecked: {
        kind: "function",
        associated: true,
        metadata: {
          since: "1.74.0",
        },
      },
      into_boxed_os_str: {
        kind: "function",
        metadata: {
          since: "1.20.0",
        },
      },
      into_encoded_bytes: {
        kind: "function",
        metadata: {
          since: "1.74.0",
        },
      },
      into_string: {
        kind: "function",
        metadata: {
          since: "1.0.0",
        },
      },
      leak: {
        kind: "function",
        metadata: {
          since: "1.89.0",
        },
      },
      new: {
        kind: "function",
        associated: true,
        metadata: {
          since: "1.0.0",
        },
      },
      push: {
        kind: "function",
        metadata: {
          since: "1.0.0",
        },
      },
      reserve: {
        kind: "function",
        metadata: {
          since: "1.9.0",
        },
      },
      reserve_exact: {
        kind: "function",
        metadata: {
          since: "1.9.0",
        },
      },
      shrink_to: {
        kind: "function",
        metadata: {
          since: "1.56.0",
        },
      },
      shrink_to_fit: {
        kind: "function",
        metadata: {
          since: "1.19.0",
        },
      },
      truncate: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      try_reserve: {
        kind: "function",
        metadata: {
          since: "1.63.0",
        },
      },
      try_reserve_exact: {
        kind: "function",
        metadata: {
          since: "1.63.0",
        },
      },
      with_capacity: {
        kind: "function",
        associated: true,
        metadata: {
          since: "1.9.0",
        },
      },
    },
  },
  VaArgSafe: {
    kind: "trait",
    canonicalCrate: "core",
  },
  VaList: {
    kind: "struct",
    canonicalCrate: "core",
    members: {
      arg: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
    },
  },
} as const satisfies Record<string, SymbolDescriptor>;

export const mod_ffi_c_str = {
  Bytes: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
  },
  CStr: {
    kind: "struct",
    canonicalCrate: "core",
    members: {
      as_c_str: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      as_ptr: {
        kind: "function",
        metadata: {
          since: "1.0.0",
        },
      },
      bytes: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      count_bytes: {
        kind: "function",
        metadata: {
          since: "1.79.0",
        },
      },
      display: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      from_bytes_until_nul: {
        kind: "function",
        associated: true,
        metadata: {
          since: "1.69.0",
        },
      },
      from_bytes_with_nul: {
        kind: "function",
        associated: true,
        metadata: {
          since: "1.10.0",
        },
      },
      from_bytes_with_nul_unchecked: {
        kind: "function",
        associated: true,
        metadata: {
          since: "1.10.0",
        },
      },
      from_ptr: {
        kind: "function",
        associated: true,
        metadata: {
          since: "1.0.0",
        },
      },
      is_empty: {
        kind: "function",
        metadata: {
          since: "1.71.0",
        },
      },
      to_bytes: {
        kind: "function",
        metadata: {
          since: "1.0.0",
        },
      },
      to_bytes_with_nul: {
        kind: "function",
        metadata: {
          since: "1.0.0",
        },
      },
      to_str: {
        kind: "function",
        metadata: {
          since: "1.4.0",
        },
      },
    },
  },
  CString: {
    kind: "struct",
    canonicalCrate: "alloc",
    members: {
      as_bytes: {
        kind: "function",
        metadata: {
          since: "1.0.0",
        },
      },
      as_bytes_with_nul: {
        kind: "function",
        metadata: {
          since: "1.0.0",
        },
      },
      as_c_str: {
        kind: "function",
        metadata: {
          since: "1.20.0",
        },
      },
      from_raw: {
        kind: "function",
        associated: true,
        metadata: {
          since: "1.4.0",
        },
      },
      from_vec_unchecked: {
        kind: "function",
        associated: true,
        metadata: {
          since: "1.0.0",
        },
      },
      from_vec_with_nul: {
        kind: "function",
        associated: true,
        metadata: {
          since: "1.58.0",
        },
      },
      from_vec_with_nul_unchecked: {
        kind: "function",
        associated: true,
        metadata: {
          since: "1.58.0",
        },
      },
      into_boxed_c_str: {
        kind: "function",
        metadata: {
          since: "1.20.0",
        },
      },
      into_bytes: {
        kind: "function",
        metadata: {
          since: "1.7.0",
        },
      },
      into_bytes_with_nul: {
        kind: "function",
        metadata: {
          since: "1.7.0",
        },
      },
      into_raw: {
        kind: "function",
        metadata: {
          since: "1.4.0",
        },
      },
      into_string: {
        kind: "function",
        metadata: {
          since: "1.7.0",
        },
      },
      new: {
        kind: "function",
        associated: true,
        metadata: {
          since: "1.0.0",
        },
      },
    },
  },
  FromBytesUntilNulError: {
    kind: "struct",
    canonicalCrate: "core",
  },
  FromBytesWithNulError: {
    kind: "enum",
    canonicalCrate: "core",
    members: {
      InteriorNul: {
        kind: "variant",
        shape: "struct",
      },
      NotNulTerminated: {
        kind: "variant",
        shape: "unit",
      },
    },
  },
  FromVecWithNulError: {
    kind: "struct",
    canonicalCrate: "alloc",
    members: {
      as_bytes: {
        kind: "function",
        metadata: {
          since: "1.58.0",
        },
      },
      into_bytes: {
        kind: "function",
        metadata: {
          since: "1.58.0",
        },
      },
    },
  },
  IntoStringError: {
    kind: "struct",
    canonicalCrate: "alloc",
    members: {
      into_cstring: {
        kind: "function",
        metadata: {
          since: "1.7.0",
        },
      },
      utf8_error: {
        kind: "function",
        metadata: {
          since: "1.7.0",
        },
      },
    },
  },
  NulError: {
    kind: "struct",
    canonicalCrate: "alloc",
    members: {
      into_vec: {
        kind: "function",
        metadata: {
          since: "1.0.0",
        },
      },
      nul_position: {
        kind: "function",
        metadata: {
          since: "1.0.0",
        },
      },
    },
  },
} as const satisfies Record<string, SymbolDescriptor>;

export const mod_ffi_os_str = {
  Display: {
    kind: "struct",
    metadata: {
      since: "1.87.0",
    },
  },
  OsStr: {
    kind: "struct",
    metadata: {
      since: "1.0.0",
    },
    members: {
      as_encoded_bytes: {
        kind: "function",
        metadata: {
          since: "1.74.0",
        },
      },
      as_os_str: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      display: {
        kind: "function",
        metadata: {
          since: "1.87.0",
        },
      },
      eq_ignore_ascii_case: {
        kind: "function",
        metadata: {
          since: "1.53.0",
        },
      },
      from_encoded_bytes_unchecked: {
        kind: "function",
        associated: true,
        metadata: {
          since: "1.74.0",
        },
      },
      into_os_string: {
        kind: "function",
        metadata: {
          since: "1.20.0",
        },
      },
      is_ascii: {
        kind: "function",
        metadata: {
          since: "1.53.0",
        },
      },
      is_empty: {
        kind: "function",
        metadata: {
          since: "1.9.0",
        },
      },
      len: {
        kind: "function",
        metadata: {
          since: "1.9.0",
        },
      },
      make_ascii_lowercase: {
        kind: "function",
        metadata: {
          since: "1.53.0",
        },
      },
      make_ascii_uppercase: {
        kind: "function",
        metadata: {
          since: "1.53.0",
        },
      },
      new: {
        kind: "function",
        associated: true,
        metadata: {
          since: "1.0.0",
        },
      },
      slice_encoded_bytes: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      to_ascii_lowercase: {
        kind: "function",
        metadata: {
          since: "1.53.0",
        },
      },
      to_ascii_uppercase: {
        kind: "function",
        metadata: {
          since: "1.53.0",
        },
      },
      to_os_string: {
        kind: "function",
        metadata: {
          since: "1.0.0",
        },
      },
      to_str: {
        kind: "function",
        metadata: {
          since: "1.0.0",
        },
      },
      to_string_lossy: {
        kind: "function",
        metadata: {
          since: "1.0.0",
        },
      },
    },
  },
  OsString: {
    kind: "struct",
    metadata: {
      since: "1.0.0",
    },
    members: {
      as_os_str: {
        kind: "function",
        metadata: {
          since: "1.0.0",
        },
      },
      capacity: {
        kind: "function",
        metadata: {
          since: "1.9.0",
        },
      },
      clear: {
        kind: "function",
        metadata: {
          since: "1.9.0",
        },
      },
      from_encoded_bytes_unchecked: {
        kind: "function",
        associated: true,
        metadata: {
          since: "1.74.0",
        },
      },
      into_boxed_os_str: {
        kind: "function",
        metadata: {
          since: "1.20.0",
        },
      },
      into_encoded_bytes: {
        kind: "function",
        metadata: {
          since: "1.74.0",
        },
      },
      into_string: {
        kind: "function",
        metadata: {
          since: "1.0.0",
        },
      },
      leak: {
        kind: "function",
        metadata: {
          since: "1.89.0",
        },
      },
      new: {
        kind: "function",
        associated: true,
        metadata: {
          since: "1.0.0",
        },
      },
      push: {
        kind: "function",
        metadata: {
          since: "1.0.0",
        },
      },
      reserve: {
        kind: "function",
        metadata: {
          since: "1.9.0",
        },
      },
      reserve_exact: {
        kind: "function",
        metadata: {
          since: "1.9.0",
        },
      },
      shrink_to: {
        kind: "function",
        metadata: {
          since: "1.56.0",
        },
      },
      shrink_to_fit: {
        kind: "function",
        metadata: {
          since: "1.19.0",
        },
      },
      truncate: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      try_reserve: {
        kind: "function",
        metadata: {
          since: "1.63.0",
        },
      },
      try_reserve_exact: {
        kind: "function",
        metadata: {
          since: "1.63.0",
        },
      },
      with_capacity: {
        kind: "function",
        associated: true,
        metadata: {
          since: "1.9.0",
        },
      },
    },
  },
} as const satisfies Record<string, SymbolDescriptor>;

export const mod_ffi_va_list = {
  VaArgSafe: {
    kind: "trait",
    canonicalCrate: "core",
  },
  VaList: {
    kind: "struct",
    canonicalCrate: "core",
    members: {
      arg: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
    },
  },
} as const satisfies Record<string, SymbolDescriptor>;
