// Generated by scripts/generate-crate-descriptor.tsx
// Source: rustdoc JSON format version 57

import type { SymbolDescriptor } from "../../create-crate.js";

export const mod_fmt = {
  Alignment: {
    kind: "enum",
    canonicalCrate: "core",
    members: {
      Center: {
        kind: "variant",
        shape: "unit",
        metadata: {
          since: "1.28.0",
        },
      },
      Left: {
        kind: "variant",
        shape: "unit",
        metadata: {
          since: "1.28.0",
        },
      },
      Right: {
        kind: "variant",
        shape: "unit",
        metadata: {
          since: "1.28.0",
        },
      },
    },
  },
  Arguments: {
    kind: "struct",
    canonicalCrate: "core",
    members: {
      as_str: {
        kind: "function",
        metadata: {
          since: "1.52.0",
        },
      },
      from_str: {
        kind: "function",
        associated: true,
        metadata: {
          since: "unstable",
        },
      },
    },
  },
  Binary: {
    kind: "trait",
    canonicalCrate: "core",
  },
  Debug: {
    kind: "trait",
    canonicalCrate: "core",
  },
  DebugAsHex: {
    kind: "enum",
    canonicalCrate: "core",
    members: {
      Lower: {
        kind: "variant",
        shape: "unit",
      },
      Upper: {
        kind: "variant",
        shape: "unit",
      },
    },
  },
  DebugList: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "1.2.0",
    },
    members: {
      entries: {
        kind: "function",
        metadata: {
          since: "1.2.0",
        },
      },
      entry: {
        kind: "function",
        metadata: {
          since: "1.2.0",
        },
      },
      entry_with: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      finish: {
        kind: "function",
        metadata: {
          since: "1.2.0",
        },
      },
      finish_non_exhaustive: {
        kind: "function",
        metadata: {
          since: "1.83.0",
        },
      },
    },
  },
  DebugMap: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "1.2.0",
    },
    members: {
      entries: {
        kind: "function",
        metadata: {
          since: "1.2.0",
        },
      },
      entry: {
        kind: "function",
        metadata: {
          since: "1.2.0",
        },
      },
      finish: {
        kind: "function",
        metadata: {
          since: "1.2.0",
        },
      },
      finish_non_exhaustive: {
        kind: "function",
        metadata: {
          since: "1.83.0",
        },
      },
      key: {
        kind: "function",
        metadata: {
          since: "1.42.0",
        },
      },
      key_with: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      value: {
        kind: "function",
        metadata: {
          since: "1.42.0",
        },
      },
      value_with: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
    },
  },
  DebugSet: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "1.2.0",
    },
    members: {
      entries: {
        kind: "function",
        metadata: {
          since: "1.2.0",
        },
      },
      entry: {
        kind: "function",
        metadata: {
          since: "1.2.0",
        },
      },
      entry_with: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      finish: {
        kind: "function",
        metadata: {
          since: "1.2.0",
        },
      },
      finish_non_exhaustive: {
        kind: "function",
        metadata: {
          since: "1.83.0",
        },
      },
    },
  },
  DebugStruct: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "1.2.0",
    },
    members: {
      field: {
        kind: "function",
        metadata: {
          since: "1.2.0",
        },
      },
      field_with: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      finish: {
        kind: "function",
        metadata: {
          since: "1.2.0",
        },
      },
      finish_non_exhaustive: {
        kind: "function",
        metadata: {
          since: "1.53.0",
        },
      },
    },
  },
  DebugTuple: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "1.2.0",
    },
    members: {
      field: {
        kind: "function",
        metadata: {
          since: "1.2.0",
        },
      },
      field_with: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      finish: {
        kind: "function",
        metadata: {
          since: "1.2.0",
        },
      },
      finish_non_exhaustive: {
        kind: "function",
        metadata: {
          since: "1.83.0",
        },
      },
    },
  },
  Display: {
    kind: "trait",
    canonicalCrate: "core",
  },
  Error: {
    kind: "struct",
    canonicalCrate: "core",
  },
  format: {
    kind: "function",
    canonicalCrate: "alloc",
    metadata: {
      since: "1.0.0",
    },
  },
  Formatter: {
    kind: "struct",
    canonicalCrate: "core",
    members: {
      align: {
        kind: "function",
        metadata: {
          since: "1.28.0",
        },
      },
      alternate: {
        kind: "function",
        metadata: {
          since: "1.5.0",
        },
      },
      debug_list: {
        kind: "function",
        metadata: {
          since: "1.2.0",
        },
      },
      debug_map: {
        kind: "function",
        metadata: {
          since: "1.2.0",
        },
      },
      debug_set: {
        kind: "function",
        metadata: {
          since: "1.2.0",
        },
      },
      debug_struct: {
        kind: "function",
        metadata: {
          since: "1.2.0",
        },
      },
      debug_tuple: {
        kind: "function",
        metadata: {
          since: "1.2.0",
        },
      },
      fill: {
        kind: "function",
        metadata: {
          since: "1.5.0",
        },
      },
      flags: {
        kind: "function",
        metadata: {
          since: "1.0.0",
        },
      },
      new: {
        kind: "function",
        associated: true,
        metadata: {
          since: "unstable",
        },
      },
      options: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      pad: {
        kind: "function",
        metadata: {
          since: "1.0.0",
        },
      },
      pad_integral: {
        kind: "function",
        metadata: {
          since: "1.0.0",
        },
      },
      precision: {
        kind: "function",
        metadata: {
          since: "1.5.0",
        },
      },
      sign: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      sign_aware_zero_pad: {
        kind: "function",
        metadata: {
          since: "1.5.0",
        },
      },
      sign_minus: {
        kind: "function",
        metadata: {
          since: "1.5.0",
        },
      },
      sign_plus: {
        kind: "function",
        metadata: {
          since: "1.5.0",
        },
      },
      width: {
        kind: "function",
        metadata: {
          since: "1.5.0",
        },
      },
      with_options: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      write_fmt: {
        kind: "function",
        metadata: {
          since: "1.0.0",
        },
      },
      write_str: {
        kind: "function",
        metadata: {
          since: "1.0.0",
        },
      },
    },
  },
  FormattingOptions: {
    kind: "struct",
    canonicalCrate: "core",
    members: {
      align: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      alternate: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      create_formatter: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      debug_as_hex: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      fill: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      get_align: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      get_alternate: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      get_debug_as_hex: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      get_fill: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      get_precision: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      get_sign: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      get_sign_aware_zero_pad: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      get_width: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      new: {
        kind: "function",
        associated: true,
        metadata: {
          since: "unstable",
        },
      },
      precision: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      sign: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      sign_aware_zero_pad: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      width: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
    },
  },
  from_fn: {
    kind: "function",
    canonicalCrate: "core",
    metadata: {
      since: "1.93.0",
    },
  },
  FromFn: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "1.93.0",
    },
  },
  LowerExp: {
    kind: "trait",
    canonicalCrate: "core",
  },
  LowerHex: {
    kind: "trait",
    canonicalCrate: "core",
  },
  NumBuffer: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
    members: {
      capacity: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      new: {
        kind: "function",
        associated: true,
        metadata: {
          since: "unstable",
        },
      },
    },
  },
  NumBufferTrait: {
    kind: "trait",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
  },
  Octal: {
    kind: "trait",
    canonicalCrate: "core",
  },
  Pointer: {
    kind: "trait",
    canonicalCrate: "core",
  },
  Result: {
    kind: "type-alias",
    canonicalCrate: "core",
  },
  Sign: {
    kind: "enum",
    canonicalCrate: "core",
    members: {
      Minus: {
        kind: "variant",
        shape: "unit",
      },
      Plus: {
        kind: "variant",
        shape: "unit",
      },
    },
  },
  UpperExp: {
    kind: "trait",
    canonicalCrate: "core",
  },
  UpperHex: {
    kind: "trait",
    canonicalCrate: "core",
  },
  write: {
    kind: "function",
    canonicalCrate: "core",
    metadata: {
      since: "1.0.0",
    },
  },
  Write: {
    kind: "trait",
    canonicalCrate: "core",
  },
} as const satisfies Record<string, SymbolDescriptor>;
