// Generated by scripts/generate-crate-descriptor.tsx
// Source: rustdoc JSON format version 57

import type { SymbolDescriptor } from "../../create-crate.js";

export const mod_marker = {
  ConstParamTy_: {
    kind: "trait",
    canonicalCrate: "core",
  },
  Copy: {
    kind: "trait",
    canonicalCrate: "core",
  },
  Destruct: {
    kind: "trait",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
  },
  DiscriminantKind: {
    kind: "trait",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
  },
  FnPtr: {
    kind: "trait",
    canonicalCrate: "core",
  },
  Freeze: {
    kind: "trait",
    canonicalCrate: "core",
  },
  MetaSized: {
    kind: "trait",
    canonicalCrate: "core",
  },
  PhantomContravariant: {
    kind: "struct",
    canonicalCrate: "core",
    members: {
      new: {
        kind: "function",
        associated: true,
      },
    },
  },
  PhantomContravariantLifetime: {
    kind: "struct",
    canonicalCrate: "core",
    members: {
      new: {
        kind: "function",
        associated: true,
      },
    },
  },
  PhantomCovariant: {
    kind: "struct",
    canonicalCrate: "core",
    members: {
      new: {
        kind: "function",
        associated: true,
      },
    },
  },
  PhantomCovariantLifetime: {
    kind: "struct",
    canonicalCrate: "core",
    members: {
      new: {
        kind: "function",
        associated: true,
      },
    },
  },
  PhantomData: {
    kind: "struct",
    canonicalCrate: "core",
  },
  PhantomInvariant: {
    kind: "struct",
    canonicalCrate: "core",
    members: {
      new: {
        kind: "function",
        associated: true,
      },
    },
  },
  PhantomInvariantLifetime: {
    kind: "struct",
    canonicalCrate: "core",
    members: {
      new: {
        kind: "function",
        associated: true,
      },
    },
  },
  PhantomPinned: {
    kind: "struct",
    canonicalCrate: "core",
  },
  PointeeSized: {
    kind: "trait",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
  },
  Send: {
    kind: "trait",
    canonicalCrate: "core",
  },
  Sized: {
    kind: "trait",
    canonicalCrate: "core",
  },
  StructuralPartialEq: {
    kind: "trait",
    canonicalCrate: "core",
  },
  Sync: {
    kind: "trait",
    canonicalCrate: "core",
  },
  Tuple: {
    kind: "trait",
    canonicalCrate: "core",
  },
  Unpin: {
    kind: "trait",
    canonicalCrate: "core",
  },
  UnsafeUnpin: {
    kind: "trait",
    canonicalCrate: "core",
  },
  Unsize: {
    kind: "trait",
    canonicalCrate: "core",
  },
  variance: {
    kind: "function",
    canonicalCrate: "core",
  },
  Variance: {
    kind: "trait",
    canonicalCrate: "core",
  },
} as const satisfies Record<string, SymbolDescriptor>;
