// Generated by scripts/generate-crate-descriptor.tsx
// Source: rustdoc JSON format version 57

import type { SymbolDescriptor } from "../../create-crate.js";

export const mod_mem = {
  align_of: {
    kind: "function",
    canonicalCrate: "core",
  },
  align_of_val: {
    kind: "function",
    canonicalCrate: "core",
  },
  align_of_val_raw: {
    kind: "function",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
  },
  Alignment: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
    members: {
      as_nonzero: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      as_nonzero_usize: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      as_usize: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      log2: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      mask: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      new: {
        kind: "function",
        associated: true,
        metadata: {
          since: "unstable",
        },
      },
      new_unchecked: {
        kind: "function",
        associated: true,
        metadata: {
          since: "unstable",
        },
      },
      of: {
        kind: "function",
        associated: true,
        metadata: {
          since: "unstable",
        },
      },
      of_val: {
        kind: "function",
        associated: true,
        metadata: {
          since: "unstable",
        },
      },
      of_val_raw: {
        kind: "function",
        associated: true,
        metadata: {
          since: "unstable",
        },
      },
    },
  },
  Assume: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
    members: {
      and: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      but_not: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
    },
  },
  conjure_zst: {
    kind: "function",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
  },
  copy: {
    kind: "function",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
  },
  discriminant: {
    kind: "function",
    canonicalCrate: "core",
    metadata: {
      since: "1.21.0",
    },
  },
  Discriminant: {
    kind: "struct",
    canonicalCrate: "core",
  },
  drop: {
    kind: "function",
    canonicalCrate: "core",
  },
  DropGuard: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
    members: {
      dismiss: {
        kind: "function",
        associated: true,
        metadata: {
          since: "unstable",
        },
      },
      new: {
        kind: "function",
        associated: true,
        metadata: {
          since: "unstable",
        },
      },
    },
  },
  forget: {
    kind: "function",
    canonicalCrate: "core",
  },
  forget_unsized: {
    kind: "function",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
  },
  ManuallyDrop: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "1.20.0",
    },
    members: {
      drop: {
        kind: "function",
        associated: true,
        metadata: {
          since: "1.20.0",
        },
      },
      into_inner: {
        kind: "function",
        associated: true,
        metadata: {
          since: "1.20.0",
        },
      },
      new: {
        kind: "function",
        associated: true,
        metadata: {
          since: "1.20.0",
        },
      },
      take: {
        kind: "function",
        associated: true,
        metadata: {
          since: "1.42.0",
        },
      },
    },
  },
  MaybeDangling: {
    kind: "struct",
    canonicalCrate: "core",
    members: {
      as_mut: {
        kind: "function",
      },
      as_ref: {
        kind: "function",
      },
      into_inner: {
        kind: "function",
      },
      new: {
        kind: "function",
        associated: true,
      },
    },
  },
  min_align_of: {
    kind: "function",
    canonicalCrate: "core",
    metadata: {
      since: "1.0.0",
    },
  },
  min_align_of_val: {
    kind: "function",
    canonicalCrate: "core",
    metadata: {
      since: "1.0.0",
    },
  },
  needs_drop: {
    kind: "function",
    canonicalCrate: "core",
  },
  offset_of: {
    kind: "symbol",
    canonicalCrate: "core",
    metadata: {
      since: "1.77.0",
    },
  },
  replace: {
    kind: "function",
    canonicalCrate: "core",
  },
  size_of: {
    kind: "function",
    canonicalCrate: "core",
  },
  size_of_val: {
    kind: "function",
    canonicalCrate: "core",
  },
  size_of_val_raw: {
    kind: "function",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
  },
  swap: {
    kind: "function",
    canonicalCrate: "core",
    metadata: {
      since: "1.0.0",
    },
  },
  take: {
    kind: "function",
    canonicalCrate: "core",
  },
  transmute: {
    kind: "function",
    canonicalCrate: "core",
    metadata: {
      since: "1.0.0",
    },
  },
  transmute_copy: {
    kind: "function",
    canonicalCrate: "core",
  },
  TransmuteFrom: {
    kind: "trait",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
  },
  uninitialized: {
    kind: "function",
    canonicalCrate: "core",
    metadata: {
      since: "1.0.0",
    },
  },
  variant_count: {
    kind: "function",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
  },
  zeroed: {
    kind: "function",
    canonicalCrate: "core",
  },
} as const satisfies Record<string, SymbolDescriptor>;

export const mod_mem_type_info = {
  Abi: {
    kind: "enum",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
    members: {
      ExternC: {
        kind: "variant",
        shape: "unit",
      },
      ExternRust: {
        kind: "variant",
        shape: "unit",
      },
      Named: {
        kind: "variant",
        shape: "tuple",
      },
    },
  },
  Array: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
  },
  Bool: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
  },
  Char: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
  },
  Const: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
  },
  DynTrait: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
  },
  DynTraitPredicate: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
  },
  Enum: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
  },
  Field: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
  },
  Float: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
  },
  FnPtr: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
  },
  Generic: {
    kind: "enum",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
    members: {
      Const: {
        kind: "variant",
        shape: "tuple",
      },
      Lifetime: {
        kind: "variant",
        shape: "tuple",
      },
      Type: {
        kind: "variant",
        shape: "tuple",
      },
    },
  },
  GenericType: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
  },
  Int: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
  },
  Lifetime: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
  },
  Pointer: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
  },
  Reference: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
  },
  Slice: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
  },
  Str: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
  },
  Struct: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
  },
  Trait: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
  },
  TraitImpl: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
    members: {
      get_vtable: {
        kind: "function",
      },
    },
  },
  Tuple: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
  },
  Type: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
    members: {
      of: {
        kind: "function",
        associated: true,
        metadata: {
          since: "unstable",
        },
      },
    },
  },
  TypeKind: {
    kind: "enum",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
    members: {
      Array: {
        kind: "variant",
        shape: "tuple",
      },
      Bool: {
        kind: "variant",
        shape: "tuple",
      },
      Char: {
        kind: "variant",
        shape: "tuple",
      },
      DynTrait: {
        kind: "variant",
        shape: "tuple",
      },
      Enum: {
        kind: "variant",
        shape: "tuple",
      },
      Float: {
        kind: "variant",
        shape: "tuple",
      },
      FnPtr: {
        kind: "variant",
        shape: "tuple",
      },
      Int: {
        kind: "variant",
        shape: "tuple",
      },
      Other: {
        kind: "variant",
        shape: "unit",
      },
      Pointer: {
        kind: "variant",
        shape: "tuple",
      },
      Reference: {
        kind: "variant",
        shape: "tuple",
      },
      Slice: {
        kind: "variant",
        shape: "tuple",
      },
      Str: {
        kind: "variant",
        shape: "tuple",
      },
      Struct: {
        kind: "variant",
        shape: "tuple",
      },
      Tuple: {
        kind: "variant",
        shape: "tuple",
      },
      Union: {
        kind: "variant",
        shape: "tuple",
      },
    },
  },
  Union: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
  },
  Variant: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
  },
} as const satisfies Record<string, SymbolDescriptor>;
