// Generated by scripts/generate-crate-descriptor.tsx
// Source: rustdoc JSON format version 57

import type { SymbolDescriptor } from "../../create-crate.js";

export const mod_num = {
  FpCategory: {
    kind: "enum",
    canonicalCrate: "core",
    members: {
      Infinite: {
        kind: "variant",
        shape: "unit",
        metadata: {
          since: "1.0.0",
        },
      },
      Nan: {
        kind: "variant",
        shape: "unit",
        metadata: {
          since: "1.0.0",
        },
      },
      Normal: {
        kind: "variant",
        shape: "unit",
        metadata: {
          since: "1.0.0",
        },
      },
      Subnormal: {
        kind: "variant",
        shape: "unit",
        metadata: {
          since: "1.0.0",
        },
      },
      Zero: {
        kind: "variant",
        shape: "unit",
        metadata: {
          since: "1.0.0",
        },
      },
    },
  },
  IntErrorKind: {
    kind: "enum",
    canonicalCrate: "core",
    members: {
      Empty: {
        kind: "variant",
        shape: "unit",
        metadata: {
          since: "1.55.0",
        },
      },
      InvalidDigit: {
        kind: "variant",
        shape: "unit",
        metadata: {
          since: "1.55.0",
        },
      },
      NegOverflow: {
        kind: "variant",
        shape: "unit",
        metadata: {
          since: "1.55.0",
        },
      },
      PosOverflow: {
        kind: "variant",
        shape: "unit",
        metadata: {
          since: "1.55.0",
        },
      },
      Zero: {
        kind: "variant",
        shape: "unit",
        metadata: {
          since: "1.55.0",
        },
      },
    },
  },
  NonZero: {
    kind: "struct",
    canonicalCrate: "core",
    members: {
      abs: {
        kind: "function",
        metadata: {
          since: "1.64.0",
        },
      },
      bit_width: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      cast_signed: {
        kind: "function",
        metadata: {
          since: "1.87.0",
        },
      },
      cast_unsigned: {
        kind: "function",
        metadata: {
          since: "1.87.0",
        },
      },
      checked_abs: {
        kind: "function",
        metadata: {
          since: "1.64.0",
        },
      },
      checked_add: {
        kind: "function",
        metadata: {
          since: "1.64.0",
        },
      },
      checked_mul: {
        kind: "function",
        metadata: {
          since: "1.64.0",
        },
      },
      checked_neg: {
        kind: "function",
        metadata: {
          since: "1.71.0",
        },
      },
      checked_next_power_of_two: {
        kind: "function",
        metadata: {
          since: "1.64.0",
        },
      },
      checked_pow: {
        kind: "function",
        metadata: {
          since: "1.64.0",
        },
      },
      count_ones: {
        kind: "function",
        metadata: {
          since: "1.86.0",
        },
      },
      div_ceil: {
        kind: "function",
        metadata: {
          since: "1.92.0",
        },
      },
      from_ascii: {
        kind: "function",
        associated: true,
        metadata: {
          since: "unstable",
        },
      },
      from_ascii_radix: {
        kind: "function",
        associated: true,
        metadata: {
          since: "unstable",
        },
      },
      from_be: {
        kind: "function",
        associated: true,
        metadata: {
          since: "unstable",
        },
      },
      from_le: {
        kind: "function",
        associated: true,
        metadata: {
          since: "unstable",
        },
      },
      from_mut: {
        kind: "function",
        associated: true,
        metadata: {
          since: "unstable",
        },
      },
      from_mut_unchecked: {
        kind: "function",
        associated: true,
        metadata: {
          since: "unstable",
        },
      },
      from_str_radix: {
        kind: "function",
        associated: true,
        metadata: {
          since: "unstable",
        },
      },
      get: {
        kind: "function",
        metadata: {
          since: "1.28.0",
        },
      },
      highest_one: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      ilog10: {
        kind: "function",
        metadata: {
          since: "1.67.0",
        },
      },
      ilog2: {
        kind: "function",
        metadata: {
          since: "1.67.0",
        },
      },
      is_negative: {
        kind: "function",
        metadata: {
          since: "1.71.0",
        },
      },
      is_positive: {
        kind: "function",
        metadata: {
          since: "1.71.0",
        },
      },
      is_power_of_two: {
        kind: "function",
        metadata: {
          since: "1.59.0",
        },
      },
      isolate_highest_one: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      isolate_lowest_one: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      isqrt: {
        kind: "function",
        metadata: {
          since: "1.84.0",
        },
      },
      leading_zeros: {
        kind: "function",
        metadata: {
          since: "1.53.0",
        },
      },
      lowest_one: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      midpoint: {
        kind: "function",
        metadata: {
          since: "1.85.0",
        },
      },
      new: {
        kind: "function",
        associated: true,
        metadata: {
          since: "1.28.0",
        },
      },
      new_unchecked: {
        kind: "function",
        associated: true,
        metadata: {
          since: "1.28.0",
        },
      },
      overflowing_abs: {
        kind: "function",
        metadata: {
          since: "1.64.0",
        },
      },
      overflowing_neg: {
        kind: "function",
        metadata: {
          since: "1.71.0",
        },
      },
      reverse_bits: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      rotate_left: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      rotate_right: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      saturating_abs: {
        kind: "function",
        metadata: {
          since: "1.64.0",
        },
      },
      saturating_add: {
        kind: "function",
        metadata: {
          since: "1.64.0",
        },
      },
      saturating_mul: {
        kind: "function",
        metadata: {
          since: "1.64.0",
        },
      },
      saturating_neg: {
        kind: "function",
        metadata: {
          since: "1.71.0",
        },
      },
      saturating_pow: {
        kind: "function",
        metadata: {
          since: "1.64.0",
        },
      },
      swap_bytes: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      to_be: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      to_le: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      trailing_zeros: {
        kind: "function",
        metadata: {
          since: "1.53.0",
        },
      },
      unchecked_add: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      unchecked_mul: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      unsigned_abs: {
        kind: "function",
        metadata: {
          since: "1.64.0",
        },
      },
      wrapping_abs: {
        kind: "function",
        metadata: {
          since: "1.64.0",
        },
      },
      wrapping_neg: {
        kind: "function",
        metadata: {
          since: "1.71.0",
        },
      },
    },
  },
  NonZeroI128: {
    kind: "type-alias",
    canonicalCrate: "core",
  },
  NonZeroI16: {
    kind: "type-alias",
    canonicalCrate: "core",
  },
  NonZeroI32: {
    kind: "type-alias",
    canonicalCrate: "core",
  },
  NonZeroI64: {
    kind: "type-alias",
    canonicalCrate: "core",
  },
  NonZeroI8: {
    kind: "type-alias",
    canonicalCrate: "core",
  },
  NonZeroIsize: {
    kind: "type-alias",
    canonicalCrate: "core",
  },
  NonZeroU128: {
    kind: "type-alias",
    canonicalCrate: "core",
  },
  NonZeroU16: {
    kind: "type-alias",
    canonicalCrate: "core",
  },
  NonZeroU32: {
    kind: "type-alias",
    canonicalCrate: "core",
  },
  NonZeroU64: {
    kind: "type-alias",
    canonicalCrate: "core",
  },
  NonZeroU8: {
    kind: "type-alias",
    canonicalCrate: "core",
  },
  NonZeroUsize: {
    kind: "type-alias",
    canonicalCrate: "core",
  },
  ParseFloatError: {
    kind: "struct",
    canonicalCrate: "core",
  },
  ParseIntError: {
    kind: "struct",
    canonicalCrate: "core",
    members: {
      kind: {
        kind: "function",
        metadata: {
          since: "1.82.0",
        },
      },
    },
  },
  Saturating: {
    kind: "struct",
    canonicalCrate: "core",
    members: {
      abs: {
        kind: "function",
        metadata: {
          since: "1.74.0",
        },
      },
      count_ones: {
        kind: "function",
        metadata: {
          since: "1.74.0",
        },
      },
      count_zeros: {
        kind: "function",
        metadata: {
          since: "1.74.0",
        },
      },
      from_be: {
        kind: "function",
        associated: true,
        metadata: {
          since: "1.74.0",
        },
      },
      from_le: {
        kind: "function",
        associated: true,
        metadata: {
          since: "1.74.0",
        },
      },
      is_negative: {
        kind: "function",
        metadata: {
          since: "1.74.0",
        },
      },
      is_positive: {
        kind: "function",
        metadata: {
          since: "1.74.0",
        },
      },
      is_power_of_two: {
        kind: "function",
        metadata: {
          since: "1.74.0",
        },
      },
      leading_zeros: {
        kind: "function",
        metadata: {
          since: "1.74.0",
        },
      },
      pow: {
        kind: "function",
        metadata: {
          since: "1.74.0",
        },
      },
      reverse_bits: {
        kind: "function",
        metadata: {
          since: "1.74.0",
        },
      },
      rotate_left: {
        kind: "function",
        metadata: {
          since: "1.74.0",
        },
      },
      rotate_right: {
        kind: "function",
        metadata: {
          since: "1.74.0",
        },
      },
      signum: {
        kind: "function",
        metadata: {
          since: "1.74.0",
        },
      },
      swap_bytes: {
        kind: "function",
        metadata: {
          since: "1.74.0",
        },
      },
      to_be: {
        kind: "function",
        metadata: {
          since: "1.74.0",
        },
      },
      to_le: {
        kind: "function",
        metadata: {
          since: "1.74.0",
        },
      },
      trailing_zeros: {
        kind: "function",
        metadata: {
          since: "1.74.0",
        },
      },
    },
  },
  TryFromIntError: {
    kind: "struct",
    canonicalCrate: "core",
  },
  Wrapping: {
    kind: "struct",
    canonicalCrate: "core",
    members: {
      abs: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      count_ones: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      count_zeros: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      from_be: {
        kind: "function",
        associated: true,
        metadata: {
          since: "unstable",
        },
      },
      from_le: {
        kind: "function",
        associated: true,
        metadata: {
          since: "unstable",
        },
      },
      is_negative: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      is_positive: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      is_power_of_two: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      leading_zeros: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      next_power_of_two: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      pow: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      reverse_bits: {
        kind: "function",
        metadata: {
          since: "1.37.0",
        },
      },
      rotate_left: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      rotate_right: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      signum: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      swap_bytes: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      to_be: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      to_le: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      trailing_zeros: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
    },
  },
  ZeroablePrimitive: {
    kind: "trait",
    canonicalCrate: "core",
  },
} as const satisfies Record<string, SymbolDescriptor>;
