// Generated by scripts/generate-crate-descriptor.tsx
// Source: rustdoc JSON format version 57

import type { SymbolDescriptor } from "../../create-crate.js";

export const mod_ops = {
  Add: {
    kind: "trait",
    canonicalCrate: "core",
    metadata: {
      since: "1.0.0",
    },
  },
  AddAssign: {
    kind: "trait",
    canonicalCrate: "core",
    metadata: {
      since: "1.8.0",
    },
  },
  AsyncFn: {
    kind: "trait",
    canonicalCrate: "core",
    metadata: {
      since: "1.85.0",
    },
  },
  AsyncFnMut: {
    kind: "trait",
    canonicalCrate: "core",
    metadata: {
      since: "1.85.0",
    },
  },
  AsyncFnOnce: {
    kind: "trait",
    canonicalCrate: "core",
    metadata: {
      since: "1.85.0",
    },
  },
  BitAnd: {
    kind: "trait",
    canonicalCrate: "core",
    metadata: {
      since: "1.0.0",
    },
  },
  BitAndAssign: {
    kind: "trait",
    canonicalCrate: "core",
    metadata: {
      since: "1.8.0",
    },
  },
  BitOr: {
    kind: "trait",
    canonicalCrate: "core",
    metadata: {
      since: "1.0.0",
    },
  },
  BitOrAssign: {
    kind: "trait",
    canonicalCrate: "core",
    metadata: {
      since: "1.8.0",
    },
  },
  BitXor: {
    kind: "trait",
    canonicalCrate: "core",
    metadata: {
      since: "1.0.0",
    },
  },
  BitXorAssign: {
    kind: "trait",
    canonicalCrate: "core",
    metadata: {
      since: "1.8.0",
    },
  },
  Bound: {
    kind: "enum",
    canonicalCrate: "core",
    metadata: {
      since: "1.17.0",
    },
    members: {
      as_mut: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      as_ref: {
        kind: "function",
        metadata: {
          since: "1.65.0",
        },
      },
      cloned: {
        kind: "function",
        metadata: {
          since: "1.55.0",
        },
      },
      copied: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      Excluded: {
        kind: "variant",
        shape: "tuple",
        metadata: {
          since: "1.17.0",
        },
      },
      Included: {
        kind: "variant",
        shape: "tuple",
        metadata: {
          since: "1.17.0",
        },
      },
      map: {
        kind: "function",
        metadata: {
          since: "1.77.0",
        },
      },
      Unbounded: {
        kind: "variant",
        shape: "unit",
        metadata: {
          since: "1.17.0",
        },
      },
    },
  },
  CoerceShared: {
    kind: "trait",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
  },
  CoerceUnsized: {
    kind: "trait",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
  },
  ControlFlow: {
    kind: "enum",
    canonicalCrate: "core",
    metadata: {
      since: "1.55.0",
    },
    members: {
      Break: {
        kind: "variant",
        shape: "tuple",
        metadata: {
          since: "1.55.0",
        },
      },
      break_ok: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      break_value: {
        kind: "function",
        metadata: {
          since: "1.83.0",
        },
      },
      Continue: {
        kind: "variant",
        shape: "tuple",
        metadata: {
          since: "1.55.0",
        },
      },
      continue_ok: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      continue_value: {
        kind: "function",
        metadata: {
          since: "1.83.0",
        },
      },
      into_value: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      is_break: {
        kind: "function",
        metadata: {
          since: "1.59.0",
        },
      },
      is_continue: {
        kind: "function",
        metadata: {
          since: "1.59.0",
        },
      },
      map_break: {
        kind: "function",
        metadata: {
          since: "1.83.0",
        },
      },
      map_continue: {
        kind: "function",
        metadata: {
          since: "1.83.0",
        },
      },
    },
  },
  Coroutine: {
    kind: "trait",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
  },
  CoroutineState: {
    kind: "enum",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
    members: {
      Complete: {
        kind: "variant",
        shape: "tuple",
      },
      Yielded: {
        kind: "variant",
        shape: "tuple",
      },
    },
  },
  Deref: {
    kind: "trait",
    canonicalCrate: "core",
    metadata: {
      since: "1.0.0",
    },
  },
  DerefMut: {
    kind: "trait",
    canonicalCrate: "core",
    metadata: {
      since: "1.0.0",
    },
  },
  DerefPure: {
    kind: "trait",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
  },
  DispatchFromDyn: {
    kind: "trait",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
  },
  Div: {
    kind: "trait",
    canonicalCrate: "core",
    metadata: {
      since: "1.0.0",
    },
  },
  DivAssign: {
    kind: "trait",
    canonicalCrate: "core",
    metadata: {
      since: "1.8.0",
    },
  },
  Drop: {
    kind: "trait",
    canonicalCrate: "core",
    metadata: {
      since: "1.0.0",
    },
  },
  Fn: {
    kind: "trait",
    canonicalCrate: "core",
    metadata: {
      since: "1.0.0",
    },
  },
  FnMut: {
    kind: "trait",
    canonicalCrate: "core",
    metadata: {
      since: "1.0.0",
    },
  },
  FnOnce: {
    kind: "trait",
    canonicalCrate: "core",
    metadata: {
      since: "1.0.0",
    },
  },
  FromResidual: {
    kind: "trait",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
  },
  Index: {
    kind: "trait",
    canonicalCrate: "core",
    metadata: {
      since: "1.0.0",
    },
  },
  IndexMut: {
    kind: "trait",
    canonicalCrate: "core",
    metadata: {
      since: "1.0.0",
    },
  },
  IntoBounds: {
    kind: "trait",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
  },
  Mul: {
    kind: "trait",
    canonicalCrate: "core",
    metadata: {
      since: "1.0.0",
    },
  },
  MulAssign: {
    kind: "trait",
    canonicalCrate: "core",
    metadata: {
      since: "1.8.0",
    },
  },
  Neg: {
    kind: "trait",
    canonicalCrate: "core",
    metadata: {
      since: "1.0.0",
    },
  },
  Not: {
    kind: "trait",
    canonicalCrate: "core",
    metadata: {
      since: "1.0.0",
    },
  },
  OneSidedRange: {
    kind: "trait",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
  },
  OneSidedRangeBound: {
    kind: "enum",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
    members: {
      End: {
        kind: "variant",
        shape: "unit",
      },
      EndInclusive: {
        kind: "variant",
        shape: "unit",
      },
      StartInclusive: {
        kind: "variant",
        shape: "unit",
      },
    },
  },
  Range: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "1.0.0",
    },
    members: {
      contains: {
        kind: "function",
        metadata: {
          since: "1.35.0",
        },
      },
      is_empty: {
        kind: "function",
        metadata: {
          since: "1.47.0",
        },
      },
    },
  },
  RangeBounds: {
    kind: "trait",
    canonicalCrate: "core",
    metadata: {
      since: "1.28.0",
    },
  },
  RangeFrom: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "1.0.0",
    },
    members: {
      contains: {
        kind: "function",
        metadata: {
          since: "1.35.0",
        },
      },
    },
  },
  RangeFull: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "1.0.0",
    },
  },
  RangeInclusive: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "1.26.0",
    },
    members: {
      contains: {
        kind: "function",
        metadata: {
          since: "1.35.0",
        },
      },
      end: {
        kind: "function",
        metadata: {
          since: "1.27.0",
        },
      },
      into_inner: {
        kind: "function",
        metadata: {
          since: "1.27.0",
        },
      },
      is_empty: {
        kind: "function",
        metadata: {
          since: "1.47.0",
        },
      },
      new: {
        kind: "function",
        associated: true,
        metadata: {
          since: "1.27.0",
        },
      },
      start: {
        kind: "function",
        metadata: {
          since: "1.27.0",
        },
      },
    },
  },
  RangeTo: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "1.0.0",
    },
    members: {
      contains: {
        kind: "function",
        metadata: {
          since: "1.35.0",
        },
      },
    },
  },
  RangeToInclusive: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "1.26.0",
    },
    members: {
      contains: {
        kind: "function",
        metadata: {
          since: "1.35.0",
        },
      },
    },
  },
  Reborrow: {
    kind: "trait",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
  },
  Receiver: {
    kind: "trait",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
  },
  Rem: {
    kind: "trait",
    canonicalCrate: "core",
    metadata: {
      since: "1.0.0",
    },
  },
  RemAssign: {
    kind: "trait",
    canonicalCrate: "core",
    metadata: {
      since: "1.8.0",
    },
  },
  Residual: {
    kind: "trait",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
  },
  Shl: {
    kind: "trait",
    canonicalCrate: "core",
    metadata: {
      since: "1.0.0",
    },
  },
  ShlAssign: {
    kind: "trait",
    canonicalCrate: "core",
    metadata: {
      since: "1.8.0",
    },
  },
  Shr: {
    kind: "trait",
    canonicalCrate: "core",
    metadata: {
      since: "1.0.0",
    },
  },
  ShrAssign: {
    kind: "trait",
    canonicalCrate: "core",
    metadata: {
      since: "1.8.0",
    },
  },
  Sub: {
    kind: "trait",
    canonicalCrate: "core",
    metadata: {
      since: "1.0.0",
    },
  },
  SubAssign: {
    kind: "trait",
    canonicalCrate: "core",
    metadata: {
      since: "1.8.0",
    },
  },
  Try: {
    kind: "trait",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
  },
  Yeet: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
  },
} as const satisfies Record<string, SymbolDescriptor>;
