// Generated by scripts/generate-crate-descriptor.tsx
// Source: rustdoc JSON format version 57

import type { SymbolDescriptor } from "../../create-crate.js";

export const mod_panic = {
  abort_unwind: {
    kind: "function",
    canonicalCrate: "core",
  },
  always_abort: {
    kind: "function",
    metadata: {
      since: "unstable",
    },
  },
  AssertUnwindSafe: {
    kind: "struct",
    canonicalCrate: "core",
  },
  BacktraceStyle: {
    kind: "enum",
    metadata: {
      since: "unstable",
    },
    members: {
      Full: {
        kind: "variant",
        shape: "unit",
      },
      Off: {
        kind: "variant",
        shape: "unit",
      },
      Short: {
        kind: "variant",
        shape: "unit",
      },
    },
  },
  catch_unwind: {
    kind: "function",
    metadata: {
      since: "1.9.0",
    },
  },
  get_backtrace_style: {
    kind: "function",
    metadata: {
      since: "unstable",
    },
  },
  Location: {
    kind: "struct",
    canonicalCrate: "core",
    members: {
      caller: {
        kind: "function",
        associated: true,
        metadata: {
          since: "1.46.0",
        },
      },
      column: {
        kind: "function",
        metadata: {
          since: "1.25.0",
        },
      },
      file: {
        kind: "function",
        metadata: {
          since: "1.10.0",
        },
      },
      file_as_c_str: {
        kind: "function",
        metadata: {
          since: "1.92.0",
        },
      },
      line: {
        kind: "function",
        metadata: {
          since: "1.10.0",
        },
      },
    },
  },
  panic_any: {
    kind: "function",
    metadata: {
      since: "1.51.0",
    },
  },
  PanicHookInfo: {
    kind: "struct",
    metadata: {
      since: "1.81.0",
    },
    members: {
      can_unwind: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      location: {
        kind: "function",
        metadata: {
          since: "1.10.0",
        },
      },
      payload: {
        kind: "function",
        metadata: {
          since: "1.10.0",
        },
      },
      payload_as_str: {
        kind: "function",
        metadata: {
          since: "1.91.0",
        },
      },
    },
  },
  PanicInfo: {
    kind: "type-alias",
    canonicalCrate: "core",
    metadata: {
      since: "1.10.0",
    },
    members: {
      can_unwind: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      location: {
        kind: "function",
        metadata: {
          since: "1.10.0",
        },
      },
      message: {
        kind: "function",
        metadata: {
          since: "1.81.0",
        },
      },
      payload: {
        kind: "function",
        metadata: {
          since: "1.10.0",
        },
      },
    },
  },
  PanicMessage: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "1.81.0",
    },
    members: {
      as_str: {
        kind: "function",
        metadata: {
          since: "1.81.0",
        },
      },
    },
  },
  RefUnwindSafe: {
    kind: "trait",
    canonicalCrate: "core",
  },
  resume_unwind: {
    kind: "function",
    metadata: {
      since: "1.9.0",
    },
  },
  set_backtrace_style: {
    kind: "function",
    metadata: {
      since: "unstable",
    },
  },
  set_hook: {
    kind: "function",
    metadata: {
      since: "1.10.0",
    },
  },
  take_hook: {
    kind: "function",
    metadata: {
      since: "1.10.0",
    },
  },
  UnwindSafe: {
    kind: "trait",
    canonicalCrate: "core",
  },
  update_hook: {
    kind: "function",
    metadata: {
      since: "unstable",
    },
  },
} as const satisfies Record<string, SymbolDescriptor>;
