// Generated by scripts/generate-crate-descriptor.tsx
// Source: rustdoc JSON format version 57

import type { SymbolDescriptor } from "../../create-crate.js";

export const mod_profiling = {
  compiler_copy: {
    kind: "function",
    metadata: {
      since: "unstable",
    },
  },
  compiler_move: {
    kind: "function",
    metadata: {
      since: "unstable",
    },
  },
} as const satisfies Record<string, SymbolDescriptor>;
