// Generated by scripts/generate-crate-descriptor.tsx
// Source: rustdoc JSON format version 57

import type { SymbolDescriptor } from "../../create-crate.js";

export const mod_ptr = {
  addr_eq: {
    kind: "function",
    canonicalCrate: "core",
    metadata: {
      since: "1.76.0",
    },
  },
  addr_of: {
    kind: "symbol",
    canonicalCrate: "core",
    metadata: {
      since: "1.51.0",
    },
  },
  addr_of_mut: {
    kind: "symbol",
    canonicalCrate: "core",
  },
  Alignment: {
    kind: "type-alias",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
  },
  copy: {
    kind: "function",
    canonicalCrate: "core",
  },
  copy_nonoverlapping: {
    kind: "function",
    canonicalCrate: "core",
  },
  dangling: {
    kind: "function",
    canonicalCrate: "core",
    metadata: {
      since: "1.84.0",
    },
  },
  dangling_mut: {
    kind: "function",
    canonicalCrate: "core",
    metadata: {
      since: "1.84.0",
    },
  },
  drop_in_place: {
    kind: "function",
    canonicalCrate: "core",
  },
  DynMetadata: {
    kind: "struct",
    canonicalCrate: "core",
    members: {
      align_of: {
        kind: "function",
      },
      layout: {
        kind: "function",
      },
      size_of: {
        kind: "function",
      },
    },
  },
  eq: {
    kind: "function",
    canonicalCrate: "core",
  },
  fn_addr_eq: {
    kind: "function",
    canonicalCrate: "core",
    metadata: {
      since: "1.85.0",
    },
  },
  from_mut: {
    kind: "function",
    canonicalCrate: "core",
    metadata: {
      since: "1.76.0",
    },
  },
  from_raw_parts: {
    kind: "function",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
  },
  from_raw_parts_mut: {
    kind: "function",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
  },
  from_ref: {
    kind: "function",
    canonicalCrate: "core",
    metadata: {
      since: "1.76.0",
    },
  },
  hash: {
    kind: "function",
    canonicalCrate: "core",
    metadata: {
      since: "1.35.0",
    },
  },
  metadata: {
    kind: "function",
    canonicalCrate: "core",
  },
  NonNull: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "1.25.0",
    },
    members: {
      add: {
        kind: "function",
        metadata: {
          since: "1.80.0",
        },
      },
      addr: {
        kind: "function",
        metadata: {
          since: "1.84.0",
        },
      },
      align_offset: {
        kind: "function",
        metadata: {
          since: "1.80.0",
        },
      },
      as_mut: {
        kind: "function",
        metadata: {
          since: "1.25.0",
        },
      },
      as_mut_ptr: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      as_non_null_ptr: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      as_ptr: {
        kind: "function",
        metadata: {
          since: "1.25.0",
        },
      },
      as_ref: {
        kind: "function",
        metadata: {
          since: "1.25.0",
        },
      },
      as_uninit_mut: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      as_uninit_ref: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      as_uninit_slice: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      as_uninit_slice_mut: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      byte_add: {
        kind: "function",
        metadata: {
          since: "1.80.0",
        },
      },
      byte_offset: {
        kind: "function",
        metadata: {
          since: "1.80.0",
        },
      },
      byte_offset_from: {
        kind: "function",
        metadata: {
          since: "1.80.0",
        },
      },
      byte_offset_from_unsigned: {
        kind: "function",
        metadata: {
          since: "1.87.0",
        },
      },
      byte_sub: {
        kind: "function",
        metadata: {
          since: "1.80.0",
        },
      },
      cast: {
        kind: "function",
        metadata: {
          since: "1.27.0",
        },
      },
      cast_array: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      cast_init: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      cast_slice: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      cast_uninit: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      copy_from: {
        kind: "function",
        metadata: {
          since: "1.80.0",
        },
      },
      copy_from_nonoverlapping: {
        kind: "function",
        metadata: {
          since: "1.80.0",
        },
      },
      copy_to: {
        kind: "function",
        metadata: {
          since: "1.80.0",
        },
      },
      copy_to_nonoverlapping: {
        kind: "function",
        metadata: {
          since: "1.80.0",
        },
      },
      dangling: {
        kind: "function",
        associated: true,
        metadata: {
          since: "1.25.0",
        },
      },
      drop_in_place: {
        kind: "function",
        metadata: {
          since: "1.80.0",
        },
      },
      expose_provenance: {
        kind: "function",
        metadata: {
          since: "1.89.0",
        },
      },
      from_mut: {
        kind: "function",
        associated: true,
        metadata: {
          since: "1.89.0",
        },
      },
      from_raw_parts: {
        kind: "function",
        associated: true,
        metadata: {
          since: "unstable",
        },
      },
      from_ref: {
        kind: "function",
        associated: true,
        metadata: {
          since: "1.89.0",
        },
      },
      get_unchecked_mut: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      is_aligned: {
        kind: "function",
        metadata: {
          since: "1.79.0",
        },
      },
      is_aligned_to: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      is_empty: {
        kind: "function",
        metadata: {
          since: "1.79.0",
        },
      },
      len: {
        kind: "function",
        metadata: {
          since: "1.63.0",
        },
      },
      map_addr: {
        kind: "function",
        metadata: {
          since: "1.84.0",
        },
      },
      new: {
        kind: "function",
        associated: true,
        metadata: {
          since: "1.25.0",
        },
      },
      new_unchecked: {
        kind: "function",
        associated: true,
        metadata: {
          since: "1.25.0",
        },
      },
      offset: {
        kind: "function",
        metadata: {
          since: "1.80.0",
        },
      },
      offset_from: {
        kind: "function",
        metadata: {
          since: "1.80.0",
        },
      },
      offset_from_unsigned: {
        kind: "function",
        metadata: {
          since: "1.87.0",
        },
      },
      read: {
        kind: "function",
        metadata: {
          since: "1.80.0",
        },
      },
      read_unaligned: {
        kind: "function",
        metadata: {
          since: "1.80.0",
        },
      },
      read_volatile: {
        kind: "function",
        metadata: {
          since: "1.80.0",
        },
      },
      replace: {
        kind: "function",
        metadata: {
          since: "1.80.0",
        },
      },
      slice_from_raw_parts: {
        kind: "function",
        associated: true,
        metadata: {
          since: "1.70.0",
        },
      },
      sub: {
        kind: "function",
        metadata: {
          since: "1.80.0",
        },
      },
      swap: {
        kind: "function",
        metadata: {
          since: "1.80.0",
        },
      },
      to_raw_parts: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      try_cast_aligned: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      with_addr: {
        kind: "function",
        metadata: {
          since: "1.84.0",
        },
      },
      with_exposed_provenance: {
        kind: "function",
        associated: true,
        metadata: {
          since: "1.89.0",
        },
      },
      without_provenance: {
        kind: "function",
        associated: true,
        metadata: {
          since: "1.89.0",
        },
      },
      write: {
        kind: "function",
        metadata: {
          since: "1.80.0",
        },
      },
      write_bytes: {
        kind: "function",
        metadata: {
          since: "1.80.0",
        },
      },
      write_unaligned: {
        kind: "function",
        metadata: {
          since: "1.80.0",
        },
      },
      write_volatile: {
        kind: "function",
        metadata: {
          since: "1.80.0",
        },
      },
    },
  },
  null: {
    kind: "function",
    canonicalCrate: "core",
  },
  null_mut: {
    kind: "function",
    canonicalCrate: "core",
  },
  Pointee: {
    kind: "trait",
    canonicalCrate: "core",
  },
  read: {
    kind: "function",
    canonicalCrate: "core",
  },
  read_unaligned: {
    kind: "function",
    canonicalCrate: "core",
  },
  read_volatile: {
    kind: "function",
    canonicalCrate: "core",
  },
  replace: {
    kind: "function",
    canonicalCrate: "core",
  },
  slice_from_raw_parts: {
    kind: "function",
    canonicalCrate: "core",
    metadata: {
      since: "1.42.0",
    },
  },
  slice_from_raw_parts_mut: {
    kind: "function",
    canonicalCrate: "core",
    metadata: {
      since: "1.42.0",
    },
  },
  swap: {
    kind: "function",
    canonicalCrate: "core",
  },
  swap_nonoverlapping: {
    kind: "function",
    canonicalCrate: "core",
    metadata: {
      since: "1.27.0",
    },
  },
  with_exposed_provenance: {
    kind: "function",
    canonicalCrate: "core",
  },
  with_exposed_provenance_mut: {
    kind: "function",
    canonicalCrate: "core",
  },
  without_provenance: {
    kind: "function",
    canonicalCrate: "core",
  },
  without_provenance_mut: {
    kind: "function",
    canonicalCrate: "core",
  },
  write: {
    kind: "function",
    canonicalCrate: "core",
  },
  write_bytes: {
    kind: "function",
    canonicalCrate: "core",
  },
  write_unaligned: {
    kind: "function",
    canonicalCrate: "core",
  },
  write_volatile: {
    kind: "function",
    canonicalCrate: "core",
  },
} as const satisfies Record<string, SymbolDescriptor>;
