// Generated by scripts/generate-crate-descriptor.tsx
// Source: rustdoc JSON format version 57

import type { SymbolDescriptor } from "../../create-crate.js";

export const mod_root = {
  assert: {
    kind: "symbol",
    canonicalCrate: "core",
  },
  assert_eq: {
    kind: "symbol",
    canonicalCrate: "core",
  },
  assert_matches: {
    kind: "symbol",
    canonicalCrate: "core",
  },
  assert_ne: {
    kind: "symbol",
    canonicalCrate: "core",
  },
  assert_unsafe_precondition: {
    kind: "symbol",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
  },
  AsyncFn: {
    kind: "trait",
  },
  AsyncFnMut: {
    kind: "trait",
  },
  AsyncFnOnce: {
    kind: "trait",
  },
  cfg: {
    kind: "symbol",
    canonicalCrate: "core",
  },
  cfg_select: {
    kind: "symbol",
    canonicalCrate: "core",
  },
  column: {
    kind: "symbol",
    canonicalCrate: "core",
  },
  compile_error: {
    kind: "symbol",
    canonicalCrate: "core",
  },
  concat: {
    kind: "symbol",
    canonicalCrate: "core",
  },
  concat_bytes: {
    kind: "symbol",
    canonicalCrate: "core",
  },
  const_format_args: {
    kind: "symbol",
    canonicalCrate: "core",
  },
  dbg: {
    kind: "symbol",
    metadata: {
      since: "unstable",
    },
  },
  debug_assert: {
    kind: "symbol",
    canonicalCrate: "core",
  },
  debug_assert_eq: {
    kind: "symbol",
    canonicalCrate: "core",
  },
  debug_assert_matches: {
    kind: "symbol",
    canonicalCrate: "core",
  },
  debug_assert_ne: {
    kind: "symbol",
    canonicalCrate: "core",
  },
  deref: {
    kind: "symbol",
  },
  DoubleEndedIterator: {
    kind: "trait",
  },
  Drop: {
    kind: "trait",
  },
  env: {
    kind: "symbol",
    canonicalCrate: "core",
  },
  eprint: {
    kind: "symbol",
    metadata: {
      since: "1.19.0",
    },
  },
  eprintln: {
    kind: "symbol",
    metadata: {
      since: "1.19.0",
    },
  },
  ExactSizeIterator: {
    kind: "trait",
  },
  Extend: {
    kind: "trait",
  },
  file: {
    kind: "symbol",
    canonicalCrate: "core",
  },
  Fn: {
    kind: "trait",
  },
  FnMut: {
    kind: "trait",
  },
  FnOnce: {
    kind: "trait",
  },
  format: {
    kind: "symbol",
    canonicalCrate: "alloc",
  },
  format_args: {
    kind: "symbol",
    canonicalCrate: "core",
  },
  hash_map: {
    kind: "symbol",
    metadata: {
      since: "unstable",
    },
  },
  include: {
    kind: "symbol",
    canonicalCrate: "core",
  },
  include_bytes: {
    kind: "symbol",
    canonicalCrate: "core",
  },
  include_str: {
    kind: "symbol",
    canonicalCrate: "core",
  },
  IntoIterator: {
    kind: "trait",
  },
  is_x86_feature_detected: {
    kind: "symbol",
  },
  Iterator: {
    kind: "trait",
  },
  line: {
    kind: "symbol",
    canonicalCrate: "core",
  },
  log_syntax: {
    kind: "symbol",
    canonicalCrate: "core",
  },
  matches: {
    kind: "symbol",
    canonicalCrate: "core",
  },
  module_path: {
    kind: "symbol",
    canonicalCrate: "core",
  },
  option_env: {
    kind: "symbol",
    canonicalCrate: "core",
  },
  panic: {
    kind: "symbol",
    canonicalCrate: "core",
    metadata: {
      since: "1.0.0",
    },
  },
  pattern_type: {
    kind: "symbol",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
  },
  print: {
    kind: "symbol",
    metadata: {
      since: "1.0.0",
    },
  },
  println: {
    kind: "symbol",
    metadata: {
      since: "1.0.0",
    },
  },
  stringify: {
    kind: "symbol",
    canonicalCrate: "core",
  },
  thread_local: {
    kind: "symbol",
    metadata: {
      since: "1.0.0",
    },
  },
  todo: {
    kind: "symbol",
    canonicalCrate: "core",
  },
  trace_macros: {
    kind: "symbol",
    canonicalCrate: "core",
  },
  try: {
    kind: "symbol",
    canonicalCrate: "core",
  },
  type_ascribe: {
    kind: "symbol",
  },
  unimplemented: {
    kind: "symbol",
    canonicalCrate: "core",
  },
  unreachable: {
    kind: "symbol",
    canonicalCrate: "core",
  },
  vec: {
    kind: "symbol",
    canonicalCrate: "alloc",
  },
  write: {
    kind: "symbol",
    canonicalCrate: "core",
  },
  writeln: {
    kind: "symbol",
    canonicalCrate: "core",
  },
} as const satisfies Record<string, SymbolDescriptor>;
