// Generated by scripts/generate-crate-descriptor.tsx
// Source: rustdoc JSON format version 57

import type { SymbolDescriptor } from "../../create-crate.js";

export const mod_slice = {
  ArrayWindows: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "1.94.0",
    },
  },
  ChunkBy: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "1.77.0",
    },
  },
  ChunkByMut: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "1.77.0",
    },
  },
  Chunks: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "1.0.0",
    },
  },
  ChunksExact: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "1.31.0",
    },
    members: {
      remainder: {
        kind: "function",
        metadata: {
          since: "1.31.0",
        },
      },
    },
  },
  ChunksExactMut: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "1.31.0",
    },
    members: {
      into_remainder: {
        kind: "function",
        metadata: {
          since: "1.31.0",
        },
      },
    },
  },
  ChunksMut: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "1.0.0",
    },
  },
  Concat: {
    kind: "trait",
    canonicalCrate: "alloc",
  },
  EscapeAscii: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "1.60.0",
    },
  },
  from_mut: {
    kind: "function",
    canonicalCrate: "core",
    metadata: {
      since: "1.28.0",
    },
  },
  from_mut_ptr_range: {
    kind: "function",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
  },
  from_ptr_range: {
    kind: "function",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
  },
  from_raw_parts: {
    kind: "function",
    canonicalCrate: "core",
    metadata: {
      since: "1.0.0",
    },
  },
  from_raw_parts_mut: {
    kind: "function",
    canonicalCrate: "core",
    metadata: {
      since: "1.0.0",
    },
  },
  from_ref: {
    kind: "function",
    canonicalCrate: "core",
    metadata: {
      since: "1.28.0",
    },
  },
  GetDisjointMutError: {
    kind: "enum",
    canonicalCrate: "core",
    members: {
      IndexOutOfBounds: {
        kind: "variant",
        shape: "unit",
      },
      OverlappingIndices: {
        kind: "variant",
        shape: "unit",
      },
    },
  },
  GetDisjointMutIndex: {
    kind: "trait",
    canonicalCrate: "core",
  },
  Iter: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "1.0.0",
    },
    members: {
      as_slice: {
        kind: "function",
        metadata: {
          since: "1.4.0",
        },
      },
    },
  },
  IterMut: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "1.0.0",
    },
    members: {
      as_mut_slice: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
      as_slice: {
        kind: "function",
        metadata: {
          since: "1.53.0",
        },
      },
      into_slice: {
        kind: "function",
        metadata: {
          since: "1.4.0",
        },
      },
    },
  },
  Join: {
    kind: "trait",
    canonicalCrate: "alloc",
  },
  range: {
    kind: "function",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
  },
  RChunks: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "1.31.0",
    },
  },
  RChunksExact: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "1.31.0",
    },
    members: {
      remainder: {
        kind: "function",
        metadata: {
          since: "1.31.0",
        },
      },
    },
  },
  RChunksExactMut: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "1.31.0",
    },
    members: {
      into_remainder: {
        kind: "function",
        metadata: {
          since: "1.31.0",
        },
      },
    },
  },
  RChunksMut: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "1.31.0",
    },
  },
  RSplit: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "1.27.0",
    },
  },
  RSplitMut: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "1.27.0",
    },
  },
  RSplitN: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "1.0.0",
    },
  },
  RSplitNMut: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "1.0.0",
    },
  },
  SliceIndex: {
    kind: "trait",
    canonicalCrate: "core",
    metadata: {
      since: "1.28.0",
    },
  },
  SlicePattern: {
    kind: "trait",
    canonicalCrate: "core",
  },
  Split: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "1.0.0",
    },
    members: {
      as_slice: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
    },
  },
  SplitInclusive: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "1.51.0",
    },
  },
  SplitInclusiveMut: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "1.51.0",
    },
  },
  SplitMut: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "1.0.0",
    },
  },
  SplitN: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "1.0.0",
    },
  },
  SplitNMut: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "1.0.0",
    },
  },
  try_range: {
    kind: "function",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
  },
  Windows: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "1.0.0",
    },
  },
} as const satisfies Record<string, SymbolDescriptor>;
