// Generated by scripts/generate-crate-descriptor.tsx
// Source: rustdoc JSON format version 57

import type { SymbolDescriptor } from "../../create-crate.js";

export const mod_str = {
  Bytes: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "1.0.0",
    },
  },
  BytesIsNotEmpty: {
    kind: "struct",
  },
  CharEscapeDebugContinue: {
    kind: "struct",
  },
  CharEscapeDefault: {
    kind: "struct",
  },
  CharEscapeUnicode: {
    kind: "struct",
  },
  CharIndices: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "1.0.0",
    },
    members: {
      as_str: {
        kind: "function",
        metadata: {
          since: "1.4.0",
        },
      },
      offset: {
        kind: "function",
        metadata: {
          since: "1.82.0",
        },
      },
    },
  },
  Chars: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "1.0.0",
    },
    members: {
      as_str: {
        kind: "function",
        metadata: {
          since: "1.4.0",
        },
      },
    },
  },
  EncodeUtf16: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "1.8.0",
    },
  },
  EscapeDebug: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "1.34.0",
    },
  },
  EscapeDefault: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "1.34.0",
    },
  },
  EscapeUnicode: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "1.34.0",
    },
  },
  from_boxed_utf8_unchecked: {
    kind: "function",
    canonicalCrate: "alloc",
    metadata: {
      since: "1.20.0",
    },
  },
  from_raw_parts: {
    kind: "function",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
  },
  from_raw_parts_mut: {
    kind: "function",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
  },
  from_utf8: {
    kind: "function",
    canonicalCrate: "core",
    metadata: {
      since: "1.0.0",
    },
  },
  from_utf8_mut: {
    kind: "function",
    canonicalCrate: "core",
    metadata: {
      since: "1.20.0",
    },
  },
  from_utf8_unchecked: {
    kind: "function",
    canonicalCrate: "core",
    metadata: {
      since: "1.0.0",
    },
  },
  from_utf8_unchecked_mut: {
    kind: "function",
    canonicalCrate: "core",
    metadata: {
      since: "1.20.0",
    },
  },
  FromStr: {
    kind: "trait",
    canonicalCrate: "core",
    metadata: {
      since: "1.0.0",
    },
  },
  IsAsciiWhitespace: {
    kind: "struct",
  },
  IsNotEmpty: {
    kind: "struct",
  },
  IsWhitespace: {
    kind: "struct",
  },
  Lines: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "1.0.0",
    },
    members: {
      remainder: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
    },
  },
  LinesAny: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "1.0.0",
    },
  },
  LinesMap: {
    kind: "struct",
  },
  Matches: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "1.2.0",
    },
  },
  MatchIndices: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "1.5.0",
    },
  },
  next_code_point: {
    kind: "function",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
  },
  ParseBoolError: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "1.0.0",
    },
  },
  RMatches: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "1.2.0",
    },
  },
  RMatchIndices: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "1.5.0",
    },
  },
  RSplit: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "1.0.0",
    },
    members: {
      remainder: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
    },
  },
  RSplitN: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "1.0.0",
    },
    members: {
      remainder: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
    },
  },
  RSplitTerminator: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "1.0.0",
    },
    members: {
      remainder: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
    },
  },
  Split: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "1.0.0",
    },
    members: {
      remainder: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
    },
  },
  SplitAsciiWhitespace: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "1.34.0",
    },
    members: {
      remainder: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
    },
  },
  SplitInclusive: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "1.51.0",
    },
    members: {
      remainder: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
    },
  },
  SplitN: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "1.0.0",
    },
    members: {
      remainder: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
    },
  },
  SplitTerminator: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "1.0.0",
    },
    members: {
      remainder: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
    },
  },
  SplitWhitespace: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "1.1.0",
    },
    members: {
      remainder: {
        kind: "function",
        metadata: {
          since: "unstable",
        },
      },
    },
  },
  UnsafeBytesToStr: {
    kind: "struct",
  },
  utf8_char_width: {
    kind: "function",
    canonicalCrate: "core",
    metadata: {
      since: "unstable",
    },
  },
  Utf8Chunk: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "1.79.0",
    },
    members: {
      invalid: {
        kind: "function",
        metadata: {
          since: "1.79.0",
        },
      },
      valid: {
        kind: "function",
        metadata: {
          since: "1.79.0",
        },
      },
    },
  },
  Utf8Chunks: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "1.79.0",
    },
  },
  Utf8Error: {
    kind: "struct",
    canonicalCrate: "core",
    metadata: {
      since: "1.0.0",
    },
    members: {
      error_len: {
        kind: "function",
        metadata: {
          since: "1.20.0",
        },
      },
      valid_up_to: {
        kind: "function",
        metadata: {
          since: "1.5.0",
        },
      },
    },
  },
} as const satisfies Record<string, SymbolDescriptor>;

export const mod_str_pattern = {
  CharArrayRefSearcher: {
    kind: "struct",
    canonicalCrate: "core",
  },
  CharArraySearcher: {
    kind: "struct",
    canonicalCrate: "core",
  },
  CharPredicateSearcher: {
    kind: "struct",
    canonicalCrate: "core",
  },
  CharSearcher: {
    kind: "struct",
    canonicalCrate: "core",
  },
  CharSliceSearcher: {
    kind: "struct",
    canonicalCrate: "core",
  },
  DoubleEndedSearcher: {
    kind: "trait",
    canonicalCrate: "core",
  },
  EmptyNeedle: {
    kind: "struct",
    canonicalCrate: "alloc",
  },
  MultiCharEqPattern: {
    kind: "struct",
    canonicalCrate: "alloc",
  },
  MultiCharEqSearcher: {
    kind: "struct",
    canonicalCrate: "alloc",
  },
  Pattern: {
    kind: "trait",
    canonicalCrate: "core",
  },
  ReverseSearcher: {
    kind: "trait",
    canonicalCrate: "core",
  },
  Searcher: {
    kind: "trait",
    canonicalCrate: "core",
  },
  SearchStep: {
    kind: "enum",
    canonicalCrate: "core",
    members: {
      Done: {
        kind: "variant",
        shape: "unit",
      },
      Match: {
        kind: "variant",
        shape: "tuple",
      },
      Reject: {
        kind: "variant",
        shape: "tuple",
      },
    },
  },
  StrSearcher: {
    kind: "struct",
    canonicalCrate: "core",
  },
  StrSearcherImpl: {
    kind: "enum",
    canonicalCrate: "alloc",
  },
  TwoWaySearcher: {
    kind: "struct",
    canonicalCrate: "alloc",
  },
  Utf8Pattern: {
    kind: "enum",
    canonicalCrate: "core",
    members: {
      CharPattern: {
        kind: "variant",
        shape: "tuple",
      },
      StringPattern: {
        kind: "variant",
        shape: "tuple",
      },
    },
  },
} as const satisfies Record<string, SymbolDescriptor>;
